INSERT INTO equipment VALUES(1,'Club','A simple wooden weapon used for bludgeoning.','weapon','common',0.1000000000000000055,2.0,'simple_melee','1d4','bludgeoning','["light"]','Slow',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(2,'Dagger','A sharp, pointed blade ideal for quick strikes.','weapon','common',2.0,1.0,'simple_melee','1d4','piercing','["finesse", "light", "thrown"]','Nick',20,60,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(3,'Greatclub','A large, heavy wooden club.','weapon','common',0.2000000000000000111,10.0,'simple_melee','1d8','bludgeoning','["two-handed"]','Push',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(4,'Handaxe','A small axe designed for throwing or melee combat.','weapon','common',5.0,2.0,'simple_melee','1d6','slashing','["light", "thrown"]','Vex',20,60,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(5,'Javelin','A light spear designed for throwing.','weapon','common',0.5,2.0,'simple_melee','1d6','piercing','["thrown"]','Slow',30,120,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(6,'Light Hammer','A small hammer suitable for throwing or close combat.','weapon','common',2.0,2.0,'simple_melee','1d4','bludgeoning','["light", "thrown"]','Nick',20,60,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(7,'Mace','A heavy club with a metal head.','weapon','common',5.0,4.0,'simple_melee','1d6','bludgeoning','[]','Sap',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(8,'Quarterstaff','A simple wooden staff.','weapon','common',0.2000000000000000111,4.0,'simple_melee','1d6','bludgeoning','["versatile"]','Topple',NULL,NULL,'1d8',NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(9,'Sickle','A curved blade on a short handle.','weapon','common',1.0,2.0,'simple_melee','1d4','slashing','["light"]','Nick',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(10,'Spear','A simple weapon with a pointed tip.','weapon','common',1.0,3.0,'simple_melee','1d6','piercing','["thrown", "versatile"]','Sap',20,60,'1d8',NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(11,'Dart','A small, pointed projectile for throwing.','weapon','common',0.05000000000000000277,0.25,'simple_ranged','1d4','piercing','["finesse", "thrown"]','Vex',20,60,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(12,'Light Crossbow','A light crossbow with mechanical advantage.','weapon','common',25.0,5.0,'simple_ranged','1d8','piercing','["ammunition", "loading", "two-handed"]','Slow',80,320,NULL,'bolt',NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(13,'Shortbow','A simple ranged weapon for hunting and combat.','weapon','common',25.0,2.0,'simple_ranged','1d6','piercing','["ammunition", "two-handed"]','Vex',80,320,NULL,'arrow',NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(14,'Sling','A simple projectile weapon using stones or bullets.','weapon','common',0.1000000000000000055,0.0,'simple_ranged','1d4','bludgeoning','["ammunition"]','Slow',30,120,NULL,'bullet',NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(15,'Battleaxe','A martial axe designed for combat.','weapon','common',10.0,4.0,'martial_melee','1d8','slashing','["versatile"]','Topple',NULL,NULL,'1d10',NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(16,'Flail','A weapon with a spiked ball on a chain.','weapon','common',10.0,2.0,'martial_melee','1d8','bludgeoning','[]','Sap',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(17,'Glaive','A polearm with a curved blade.','weapon','common',20.0,6.0,'martial_melee','1d10','slashing','["heavy", "reach", "two-handed"]','Graze',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(18,'Greataxe','A large, two-handed axe.','weapon','common',30.0,7.0,'martial_melee','1d12','slashing','["heavy", "two-handed"]','Cleave',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(19,'Greatsword','A massive two-handed sword for powerful strikes. Proficiency allows you to add your proficiency bonus to attack rolls.','weapon','common',50.0,6.0,'martial_melee','2d6','slashing','["heavy", "two-handed", "graze"]','Graze',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(20,'Halberd','A polearm with an axe blade and spike.','weapon','common',20.0,6.0,'martial_melee','1d10','slashing','["heavy", "reach", "two-handed"]','Cleave',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(21,'Lance','A long weapon designed for mounted combat.','weapon','common',10.0,6.0,'martial_melee','1d10','piercing','["heavy", "reach", "two-handed-unless-mounted"]','Topple',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(22,'Longsword','A versatile martial weapon favored by many warriors.','weapon','common',15.0,3.0,'martial_melee','1d8','slashing','["versatile"]','Sap',NULL,NULL,'1d10',NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(23,'Maul','A heavy, two-handed hammer.','weapon','common',10.0,10.0,'martial_melee','2d6','bludgeoning','["heavy", "two-handed"]','Topple',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(24,'Morningstar','A spiked mace with additional piercing damage.','weapon','common',15.0,4.0,'martial_melee','1d8','piercing','[]','Sap',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(25,'Pike','A very long spear for infantry formations.','weapon','common',5.0,18.0,'martial_melee','1d10','piercing','["heavy", "reach", "two-handed"]','Push',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(26,'Rapier','A slender, precise thrusting weapon.','weapon','common',25.0,2.0,'martial_melee','1d8','piercing','["finesse"]','Vex',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(27,'Scimitar','A curved sword with a light design.','weapon','common',25.0,3.0,'martial_melee','1d6','slashing','["finesse", "light"]','Nick',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(28,'Shortsword','A light, finesse weapon ideal for quick strikes.','weapon','common',10.0,2.0,'martial_melee','1d6','piercing','["finesse", "light"]','Vex',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(29,'Trident','A three-pronged spear.','weapon','common',5.0,4.0,'martial_melee','1d8','piercing','["thrown", "versatile"]','Topple',20,60,'1d10',NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(30,'Warhammer','A one-handed war hammer with versatile grip.','weapon','common',15.0,5.0,'martial_melee','1d8','bludgeoning','["versatile"]','Push',NULL,NULL,'1d10',NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(31,'War Pick','A pick designed for piercing armor.','weapon','common',5.0,2.0,'martial_melee','1d8','piercing','["versatile"]','Sap',NULL,NULL,'1d10',NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(32,'Whip','A flexible weapon with reach.','weapon','common',2.0,3.0,'martial_melee','1d4','slashing','["finesse", "reach"]','Slow',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(33,'Blowgun','A tube for shooting needles with stealth.','weapon','common',10.0,1.0,'martial_ranged','1','piercing','["ammunition", "loading"]','Vex',25,100,NULL,'needle',NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(34,'Hand Crossbow','A small crossbow that can be used in one hand.','weapon','common',75.0,3.0,'martial_ranged','1d6','piercing','["ammunition", "light", "loading"]','Vex',30,120,NULL,'bolt',NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(35,'Heavy Crossbow','A powerful, two-handed crossbow.','weapon','common',50.0,18.0,'martial_ranged','1d10','piercing','["ammunition", "heavy", "loading", "two-handed"]','Push',100,400,NULL,'bolt',NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(36,'Longbow','A tall bow with exceptional range.','weapon','common',50.0,2.0,'martial_ranged','1d8','piercing','["ammunition", "heavy", "two-handed"]','Slow',150,600,NULL,'arrow',NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(37,'Musket','A primitive firearm with black powder.','weapon','uncommon',500.0,10.0,'martial_ranged','1d12','piercing','["ammunition", "loading", "two-handed"]','Slow',40,120,NULL,'bullet',NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(38,'Pistol','A small firearm designed for one-handed use.','weapon','uncommon',250.0,3.0,'martial_ranged','1d10','piercing','["ammunition", "loading"]','Vex',30,90,NULL,'bullet',NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(39,'Leather Armor','Light armor made from supple and thin leather.','armor','common',10.0,10.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,11,'light',NULL,NULL,0,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(40,'Chain Mail','Heavy armor made of interlocking metal rings.','armor','common',75.0,55.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16,'heavy',NULL,13,1,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(41,'Shield','A shield made from wood or metal, increases AC by 2.','shield','common',10.0,6.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(42,'Studded Leather','Made from tough but flexible leather, studded leather is reinforced with close-set rivets or spikes.','armor','common',45.0,13.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,12,'light',NULL,NULL,0,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(43,'Breastplate','This armor consists of a fitted metal chest piece worn with supple leather.','armor','common',400.0,20.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,14,'medium',2,NULL,0,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(44,'Chain Shirt','Made of interlocking metal rings, a chain shirt is worn between layers of clothing or leather.','armor','common',50.0,20.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,13,'medium',2,NULL,0,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(45,'Scale Mail','This armor consists of a coat and leggings of leather covered with overlapping pieces of metal.','armor','common',50.0,45.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,14,'medium',2,NULL,1,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(46,'Half Plate','Half plate consists of shaped metal plates that cover most of the wearer''s body.','armor','common',750.0,40.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,15,'medium',2,NULL,1,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(47,'Plate Armor','Plate consists of shaped, interlocking metal plates to cover the entire body.','armor','common',1500.0,65.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,18,'heavy',NULL,15,1,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(48,'Mithral Chain Mail','This fine chain mail is made of mithral, removing its normal restrictions.','armor','uncommon',4075.0,27.5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16,'heavy',NULL,NULL,0,1,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(49,'Backpack','A leather backpack that can hold up to 30 pounds of gear.','gear','common',2.0,5.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(50,'Potion of Healing','This potion is a magic item. As a Bonus Action, you can drink it or administer it to another creature within 5 feet of yourself. The creature that drinks the magical red fluid in this vial regains 2d4 + 2 Hit Points.','consumable','common',50.0,0.5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(51,'Rations (5 days)','These are required to gain the benefits of a long rest. Each day''s ration provides enough sustenance for one creature for 24 hours.','consumable','common',5.0,10.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(52,'Empty Bottle','A glass bottle that once contained a potion. Can be sold or refilled by an alchemist.','miscellaneous','common',0.0100000000000000002,0.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(53,'Arcane Focus','A spellcasting focus used by wizards, sorcerers, and warlocks.','spellcasting_focus','common',20.0,1.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(54,'Holy Symbol','A divine spellcasting focus used by clerics and paladins.','spellcasting_focus','common',5.0,1.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(55,'Spellbook','A book containing spells and magical formulae.','spellbook','common',50.0,3.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO equipment VALUES(56,'Dread Helm','A fearsome helmet that strikes terror into enemies.','helmet','uncommon',25.0,2.0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'2025-09-02T21:58:07.448528');
INSERT INTO classes VALUES('fighter','Fighter','A master of martial combat, skilled with a variety of weapons and armor.',10,'Strength or Dexterity',2,'{"armor": "chain_mail", "weapons": ["shield"], "equipment": ["dungeoneer_pack", "javelin_2"]}','[{"name": "Martial Weapon", "choice_type": "weapon", "options": ["longsword", "greatsword", "rapier"], "max_selections": 1, "is_required": true}, {"name": "Armor", "choice_type": "armor", "options": ["studded leather", "breastplate", "chain mail"], "max_selections": 1, "is_required": true}]',0);
INSERT INTO classes VALUES('barbarian','Barbarian','A fierce warrior of primitive background who can enter a battle rage.',12,'Strength',2,'{}','[]',1);
INSERT INTO classes VALUES('cleric','Cleric','A priestly champion who wields divine magic in service of a higher power.',8,'Wisdom',2,'{}','[]',2);
INSERT INTO classes VALUES('paladin','Paladin','A holy warrior bound to a sacred oath, wielding divine magic.',10,'Strength and Charisma',2,'{}','[]',3);
INSERT INTO classes VALUES('rogue','Rogue','A scoundrel who uses stealth and trickery to overcome obstacles.',8,'Dexterity',4,'{"armor": "leather_armor", "weapons": ["rapier", "shortbow"], "equipment": ["burglar_pack", "thieves_tools"]}','[]',4);
INSERT INTO classes VALUES('warlock','Warlock','A wielder of magic derived from a bargain with an extraplanar entity.',8,'Charisma',2,'{}','[]',5);
INSERT INTO classes VALUES('wizard','Wizard','A scholarly magic-user capable of manipulating the structures of spellcasting.',6,'Intelligence',2,'{}','[]',6);
INSERT INTO backgrounds VALUES('farmer','Farmer','You know the hard work of the farm and field. You understand the cycle of seasons and the patience required to nurture crops and livestock.','["Animal Handling", "Nature"]','[]','["Carpenter''s Tools"]','{"option_a": {"equipment": ["carpenters_tools", "shovel", "common_clothes", "belt_pouch", "backpack", "potion_of_healing", "rations_5"], "gold": 10}, "option_b": {"gold": 50}}','["carpenters_tools", "shovel", "common_clothes", "belt_pouch", "backpack", "potion_of_healing", "rations_5"]',10,'','','Tough',0);
INSERT INTO backgrounds VALUES('soldier','Soldier','You began training for war as soon as you reached adulthood and carry precious few memories of life before you took up arms. Battle is in your blood. The crash of weapons, the stink of blood, the screams of enemies—this is the music that makes your heart race. War has been your life for as long as you care to remember.','["Athletics", "Intimidation"]','[]','["Gaming Set"]','{"option_a": {"equipment": ["spear", "shortbow", "arrows_20", "gaming_set", "healers_kit", "quiver", "travelers_clothes"], "gold": 14}, "option_b": {"gold": 50}}','["spear", "shortbow", "arrows_20", "gaming_set", "healers_kit", "quiver", "travelers_clothes"]',14,'','','Savage Attacker',1);
INSERT INTO backgrounds VALUES('acolyte','Acolyte','You devoted yourself to service in a temple, either nestled in a town or secluded in a sacred grove. There you performed rites in honor of a god or pantheon. You served under a priest and studied religion. Thanks to your priest''s instruction and your own devotion, you gained mastery over your god''s mysteries.','["Insight", "Religion"]','[]','["Calligrapher''s Supplies"]','{"option_a": {"equipment": ["calligraphers_supplies", "prayer_book", "holy_symbol", "parchment_10", "robe"], "gold": 8}, "option_b": {"gold": 50}}','["calligraphers_supplies", "prayer_book", "holy_symbol", "parchment_10", "robe"]',8,'','','Magic Initiate (Cleric)',2);
INSERT INTO backgrounds VALUES('criminal','Criminal','You once broke the law and paid for it, learning a hard lesson about the reach of legal authority. You spent time among other criminals and developed connections within the criminal underworld. You''re far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization.','["Sleight of Hand", "Stealth"]','[]','["Thieves'' Tools"]','{"option_a": {"equipment": ["dagger", "dagger", "thieves_tools", "crowbar", "pouch", "pouch", "travelers_clothes"], "gold": 16}, "option_b": {"gold": 50}}','["dagger", "dagger", "thieves_tools", "crowbar", "pouch", "pouch", "travelers_clothes"]',16,'','','Alert',3);
INSERT INTO backgrounds VALUES('sage','Sage','You spent your formative years traveling between libraries, scriptoriums, and universities, learning from scholars, wizards, and other learned persons. You became an apprentice to a master who taught you to value knowledge above all else. You mastered the basics of accessing the most fundamental sources of knowledge.','["Arcana", "History"]','[]','["Calligrapher''s Supplies"]','{"option_a": {"equipment": ["quarterstaff", "calligraphers_supplies", "history_book", "parchment_8", "robe"], "gold": 8}, "option_b": {"gold": 50}}','["quarterstaff", "calligraphers_supplies", "history_book", "parchment_8", "robe"]',8,'','','Magic Initiate (Wizard)',4);
INSERT INTO races VALUES('human','Human','Versatile and ambitious, humans are the most common race in most D&D worlds.','Medium',30,'{}','{"resourceful": "You gain Heroic Inspiration whenever you finish a Long Rest.", "skillful": "You gain proficiency in one skill of your choice.", "versatile": "You gain an Origin feat of your choice."}','["Common"]','[]',0);
INSERT INTO races VALUES('dwarf','Dwarf','Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.','Medium',25,'{}','{"darkvision": "You have Darkvision with a range of 120 feet.", "dwarven_resilience": "You have Resistance to Poison damage. You also have Advantage on saving throws you make to avoid or end the Poisoned condition.", "dwarven_toughness": "Your Hit Point maximum increases by 1, and it increases by 1 again whenever you gain a level."}','["Common", "Dwarvish"]','[]',1);
INSERT INTO feats VALUES('ability_score_improvement','Ability Score Improvement','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('actor','Actor','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('alert','Alert','You gain the following benefits: Initiative Proficiency - When you roll Initiative, you can add your Proficiency Bonus to the roll.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('archery','Archery','You gain a +2 bonus to attack rolls you make with ranged weapons.','[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]','{}','{}','SRD','fighting_style');
INSERT INTO feats VALUES('athlete','Athlete','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('blessed_warrior','Blessed Warrior','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('blind_fighting','Blind Fighting','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_combat_prowess','Boon of Combat Prowess','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_dimensional_travel','Boon of Dimensional Travel','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_energy_resistance','Boon of Energy Resistance','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_fate','Boon of Fate','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_fortitude','Boon of Fortitude','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_irresistible_offense','Boon of Irresistible Offense','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_recovery','Boon of Recovery','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_skill','Boon of Skill','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_speed','Boon of Speed','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_spell_recall','Boon of Spell Recall','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_truesight','Boon of Truesight','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('boon_of_the_night_spirit','Boon of the Night Spirit','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('charger','Charger','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('chef','Chef','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('crafter','Crafter','You are practiced in the crafting of one or more objects and the selling of those objects. You gain proficiency with three different artisan tools of your choice.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('crossbow_expert','Crossbow Expert','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('crusher','Crusher','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('defense','Defense','While you are wearing armor, you gain a +1 bonus to AC.','[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]','{}','{}','SRD','fighting_style');
INSERT INTO feats VALUES('defensive_duelist','Defensive Duelist','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('druidic_warrior','Druidic Warrior','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('dual_wielder','Dual Wielder','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('dueling','Dueling','When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.','[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]','{}','{}','SRD','fighting_style');
INSERT INTO feats VALUES('dungeon_delver','Dungeon Delver','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('durable','Durable','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('elemental_adept','Elemental Adept','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('fey-touched','Fey-Touched','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('grappler','Grappler','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('great_weapon_fighting','Great Weapon Fighting','When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll, even if the new roll is a 1 or a 2.','[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]','{}','{}','SRD','fighting_style');
INSERT INTO feats VALUES('great_weapon_master','Great Weapon Master','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('heavily_armored','Heavily Armored','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('heavy_armor_master','Heavy Armor Master','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('interception','Interception','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('keen_mind','Keen Mind','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('lightly_armored','Lightly Armored','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('linguist','Linguist','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('lucky','Lucky','You gain the following benefits: Luck Points - You have a number of Luck Points equal to your Proficiency Bonus and can spend the points on the benefits below. You regain your expended Luck Points when you finish a Long Rest. Advantage - When you roll a d20 for a D20 Test, you can spend 1 Luck Point to give yourself Advantage on the roll. Disadvantage - When a creature rolls a d20 for an attack roll against you, you can spend 1 Luck Point to impose Disadvantage on that roll.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('mage_slayer','Mage Slayer','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('martial_adept','Martial Adept','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('martial_weapon_training','Martial Weapon Training','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('medium_armor_master','Medium Armor Master','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('mobile','Mobile','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('moderately_armored','Moderately Armored','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('mounted_combatant','Mounted Combatant','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('musician','Musician','You gain the following benefits: Instrument Training - You gain proficiency with three Musical Instruments of your choice. Encouraging Song - As you finish a Short or Long Rest, you can play a song on a Musical Instrument with which you have proficiency and give Heroic Inspiration to allies who hear the song. The number of allies you can affect in this way equals your Proficiency Bonus.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('piercer','Piercer','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('poisoner','Poisoner','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('polearm_master','Polearm Master','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('protection','Protection','When a creature you can see attacks a target other than you that is within 5 feet of you, you can use your reaction to impose disadvantage on the attack roll. You must be wielding a shield.','[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]','{}','{}','SRD','fighting_style');
INSERT INTO feats VALUES('savage_attacker','Savage Attacker','You''ve trained to deal particularly damaging strikes. Once per turn when you hit a target with a weapon, you can roll the weapon''s damage dice twice and use either roll against the target.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('shadow-touched','Shadow-Touched','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('sharpshooter','Sharpshooter','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('shield_master','Shield Master','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('skill_expert','Skill Expert','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('skilled','Skilled','You have a knack for learning new things. You gain proficiency in any combination of three skills or tools of your choice.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('skulker','Skulker','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('slasher','Slasher','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('speedy','Speedy','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('spell_sniper','Spell Sniper','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('tavern_brawler','Tavern Brawler','You gain the following benefits: Enhanced Unarmed Strike - When you hit with your Unarmed Strike and deal damage, you can deal Bludgeoning damage equal to 1d4 plus your Strength modifier instead of the normal damage of an Unarmed Strike. Damage Rerolls - Whenever you roll a damage die for your Unarmed Strike, you can reroll the die if it rolls a 1, and you must use the new roll.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('thrown_weapon_fighting','Thrown Weapon Fighting','You can draw a weapon that has the thrown property as part of the attack you make with the weapon. In addition, when you hit with a ranged attack using a thrown weapon, you gain a +2 bonus to the damage roll.','[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]','{}','{}','SRD','fighting_style');
INSERT INTO feats VALUES('tough','Tough','Your Hit Point maximum increases by an amount equal to twice your character level when you gain this feat. Whenever you gain a character level thereafter, your Hit Point maximum increases by an additional 2 Hit Points.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('two-weapon_fighting','Two-Weapon Fighting','When you engage in two-weapon fighting, you can add your ability modifier to the damage of the second attack.','[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]','{}','{}','SRD','fighting_style');
INSERT INTO feats VALUES('unarmed_fighting','Unarmed Fighting','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('weapon_master','Weapon Master','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('magic_initiate_cleric','Magic Initiate (Cleric)','You have learned magical theory or been exposed to elemental forces. You learn spells from the Cleric class.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('magic_initiate_wizard','Magic Initiate (Wizard)','You have learned magical theory or been exposed to elemental forces. You learn spells from the Wizard class.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('healer','Healer','You gain the following benefits: Battle Medic - If you have a Healer''s Kit, you can expend one use of it and tend to a creature within 5 feet of yourself as a Utilize action. That creature can expend one of its Hit Point Dice, and you then roll that die. The creature regains a number of Hit Points equal to the roll plus your Proficiency Bonus. Healing Rerolls - Whenever you roll a die to determine the number of Hit Points you restore with a spell or with this feat''s Battle Medic benefit, you can reroll the die if it rolls a 1, and you must use the new roll.','[]','{}','{}','SRD','O');
INSERT INTO feats VALUES('inspiring_leader','Inspiring Leader','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('observant','Observant','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('resilient','Resilient','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('ritual_caster','Ritual Caster','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('sentinel','Sentinel','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('telekinetic','Telekinetic','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('telepathic','Telepathic','','[]','{}','{}','SRD','general');
INSERT INTO feats VALUES('war_caster','War Caster','','[]','{}','{}','SRD','general');
INSERT INTO weapon_masteries VALUES(1,'Cleave','on_hit','If you hit a creature with a melee attack roll using this weapon, you can make a melee attack roll with the weapon against a second creature within 5 feet of the first that is also within your reach. On a hit, the second creature takes the weapon''s damage, but don''t add your ability modifier to that damage unless that modifier is negative. You can make this extra attack only once per turn.',0,NULL,NULL,'weapon_damage_no_modifier','extra_attack_adjacent');
INSERT INTO weapon_masteries VALUES(2,'Graze','on_miss','If your attack roll with this weapon misses a creature, you can deal damage to that creature equal to the ability modifier you used to make the attack roll. This damage is the same type dealt by the weapon, and the damage can be increased only by increasing the ability modifier.',0,NULL,NULL,'ability_modifier','damage_on_miss');
INSERT INTO weapon_masteries VALUES(3,'Nick','on_hit','When you make the extra attack of the Light property, you can make it as part of the Attack action instead of as a Bonus Action. You can make this extra attack only once per turn.',0,NULL,NULL,NULL,'light_attack_as_action');
INSERT INTO weapon_masteries VALUES(4,'Push','on_hit','If you hit a creature with this weapon, you can push the creature up to 10 feet straight away from yourself if it is Large or smaller.',0,NULL,NULL,NULL,'push_10_feet');
INSERT INTO weapon_masteries VALUES(5,'Sap','on_hit','If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.',0,NULL,NULL,NULL,'disadvantage_next_attack');
INSERT INTO weapon_masteries VALUES(6,'Slow','on_hit','If you hit a creature with this weapon and deal damage to it, you can reduce its Speed by 10 feet until the start of your next turn. If the creature is hit more than once by weapons that have this property, the Speed reduction doesn''t exceed 10 feet.',0,NULL,NULL,NULL,'reduce_speed_10');
INSERT INTO weapon_masteries VALUES(7,'Topple','on_hit','If you hit a creature with this weapon, you can force the creature to make a Constitution saving throw (DC 8 plus the ability modifier used to make the attack roll and your Proficiency Bonus). On a failed save, the creature has the Prone condition.',1,'Constitution','8 + ability_modifier + proficiency_bonus',NULL,'prone_on_failed_save');
INSERT INTO weapon_masteries VALUES(8,'Vex','on_hit','If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.',0,NULL,NULL,NULL,'advantage_next_attack');
INSERT INTO class_equipment_choices VALUES(3,'barbarian','weapon_choice','Weapon Choice','["Shield + Spear", "Greataxe", "2x Scimitars"]','2025-09-02 13:33:05');
INSERT INTO class_equipment_choices VALUES(4,'barbarian','armor_choice','Armor/Helmet Choice','["Dread Helm", "Scale Mail", "Chain Mail"]','2025-09-02 13:33:05');
INSERT INTO class_equipment_choices VALUES(5,'rogue','armor_choice','Armor','["Studded Leather"]','2025-09-02 13:33:05');
INSERT INTO class_equipment_choices VALUES(6,'rogue','weapon_choice','Weapon Choice','["Rapier + Dagger", "Scimitar + Shortsword"]','2025-09-02 13:33:05');
INSERT INTO class_equipment_choices VALUES(7,'cleric','equipment_choice','Equipment','["Holy Symbol + Scale Mail + Mace + Shield", "Holy Symbol + Chain Mail + Mace + Shield"]','2025-09-02 13:33:13');
INSERT INTO class_equipment_choices VALUES(8,'paladin','equipment_choice','Equipment Choice','["Holy Symbol + Scale Mail + Longsword + Shield", "Holy Symbol + Chain Mail + Longsword + Shield", "Holy Symbol + Scale Mail + Greatsword", "Holy Symbol + Chain Mail + Greatsword"]','2025-09-02 13:33:13');
INSERT INTO class_equipment_choices VALUES(9,'wizard','equipment_choice','Equipment Choice','["Arcane Focus + Spellbook + Quarterstaff", "Arcane Focus + Spellbook + Dagger"]','2025-09-02 13:33:13');
INSERT INTO class_equipment_choices VALUES(10,'warlock','equipment_auto','Starting Equipment','["Studded Leather + Arcane Focus + Spear"]','2025-09-02 13:33:20');
INSERT INTO class_equipment_choices VALUES(11,'fighter','armor_choice','Armor Choice','["Studded Leather", "Scale Mail", "Chain Mail"]','2025-09-04 02:45:31');
INSERT INTO class_equipment_choices VALUES(12,'fighter','weapon_choice','Weapon Choice','["Greatsword", "Longsword + Shield", "Scimitar + Scimitar"]','2025-09-04 02:45:31');
INSERT INTO level_progression VALUES(1,0,2);
INSERT INTO level_progression VALUES(2,300,2);
INSERT INTO level_progression VALUES(3,900,2);
INSERT INTO level_progression VALUES(4,2700,2);
INSERT INTO level_progression VALUES(5,6500,3);
INSERT INTO level_progression VALUES(6,14000,3);
INSERT INTO level_progression VALUES(7,23000,3);
INSERT INTO level_progression VALUES(8,34000,3);
INSERT INTO level_progression VALUES(9,48000,4);
INSERT INTO level_progression VALUES(10,64000,4);
INSERT INTO level_progression VALUES(11,85000,4);
INSERT INTO level_progression VALUES(12,100000,4);
INSERT INTO level_progression VALUES(13,120000,5);
INSERT INTO level_progression VALUES(14,140000,5);
INSERT INTO level_progression VALUES(15,165000,5);
INSERT INTO level_progression VALUES(16,195000,5);
INSERT INTO level_progression VALUES(17,225000,6);
INSERT INTO level_progression VALUES(18,265000,6);
INSERT INTO level_progression VALUES(19,305000,6);
INSERT INTO level_progression VALUES(20,355000,6);
INSERT INTO class_saving_throws VALUES('fighter','strength');
INSERT INTO class_saving_throws VALUES('fighter','constitution');
INSERT INTO class_saving_throws VALUES('barbarian','strength');
INSERT INTO class_saving_throws VALUES('barbarian','constitution');
INSERT INTO class_saving_throws VALUES('cleric','wisdom');
INSERT INTO class_saving_throws VALUES('cleric','charisma');
INSERT INTO class_saving_throws VALUES('paladin','wisdom');
INSERT INTO class_saving_throws VALUES('paladin','charisma');
INSERT INTO class_saving_throws VALUES('rogue','dexterity');
INSERT INTO class_saving_throws VALUES('rogue','intelligence');
INSERT INTO class_saving_throws VALUES('warlock','wisdom');
INSERT INTO class_saving_throws VALUES('warlock','charisma');
INSERT INTO class_saving_throws VALUES('wizard','intelligence');
INSERT INTO class_saving_throws VALUES('wizard','wisdom');
INSERT INTO class_armor_proficiencies VALUES('fighter','light');
INSERT INTO class_armor_proficiencies VALUES('fighter','medium');
INSERT INTO class_armor_proficiencies VALUES('fighter','heavy');
INSERT INTO class_armor_proficiencies VALUES('fighter','shields');
INSERT INTO class_armor_proficiencies VALUES('barbarian','light');
INSERT INTO class_armor_proficiencies VALUES('barbarian','medium');
INSERT INTO class_armor_proficiencies VALUES('barbarian','shields');
INSERT INTO class_armor_proficiencies VALUES('cleric','light');
INSERT INTO class_armor_proficiencies VALUES('cleric','medium');
INSERT INTO class_armor_proficiencies VALUES('cleric','shields');
INSERT INTO class_armor_proficiencies VALUES('paladin','light');
INSERT INTO class_armor_proficiencies VALUES('paladin','medium');
INSERT INTO class_armor_proficiencies VALUES('paladin','heavy');
INSERT INTO class_armor_proficiencies VALUES('paladin','shields');
INSERT INTO class_armor_proficiencies VALUES('rogue','light');
INSERT INTO class_armor_proficiencies VALUES('warlock','light');
INSERT INTO class_weapon_proficiencies VALUES('fighter','simple');
INSERT INTO class_weapon_proficiencies VALUES('fighter','martial');
INSERT INTO class_weapon_proficiencies VALUES('barbarian','simple');
INSERT INTO class_weapon_proficiencies VALUES('barbarian','martial');
INSERT INTO class_weapon_proficiencies VALUES('cleric','simple');
INSERT INTO class_weapon_proficiencies VALUES('paladin','simple');
INSERT INTO class_weapon_proficiencies VALUES('paladin','martial');
INSERT INTO class_weapon_proficiencies VALUES('rogue','simple');
INSERT INTO class_weapon_proficiencies VALUES('rogue','hand_crossbow');
INSERT INTO class_weapon_proficiencies VALUES('rogue','longsword');
INSERT INTO class_weapon_proficiencies VALUES('rogue','rapier');
INSERT INTO class_weapon_proficiencies VALUES('rogue','shortsword');
INSERT INTO class_weapon_proficiencies VALUES('warlock','simple');
INSERT INTO class_weapon_proficiencies VALUES('wizard','daggers');
INSERT INTO class_weapon_proficiencies VALUES('wizard','darts');
INSERT INTO class_weapon_proficiencies VALUES('wizard','slings');
INSERT INTO class_weapon_proficiencies VALUES('wizard','quarterstaffs');
INSERT INTO class_weapon_proficiencies VALUES('wizard','light crossbows');
INSERT INTO class_skill_proficiencies VALUES('fighter','Acrobatics');
INSERT INTO class_skill_proficiencies VALUES('fighter','Animal Handling');
INSERT INTO class_skill_proficiencies VALUES('fighter','Athletics');
INSERT INTO class_skill_proficiencies VALUES('fighter','History');
INSERT INTO class_skill_proficiencies VALUES('fighter','Insight');
INSERT INTO class_skill_proficiencies VALUES('fighter','Intimidation');
INSERT INTO class_skill_proficiencies VALUES('fighter','Perception');
INSERT INTO class_skill_proficiencies VALUES('fighter','Survival');
INSERT INTO class_skill_proficiencies VALUES('barbarian','Animal Handling');
INSERT INTO class_skill_proficiencies VALUES('barbarian','Athletics');
INSERT INTO class_skill_proficiencies VALUES('barbarian','Intimidation');
INSERT INTO class_skill_proficiencies VALUES('barbarian','Nature');
INSERT INTO class_skill_proficiencies VALUES('barbarian','Perception');
INSERT INTO class_skill_proficiencies VALUES('barbarian','Survival');
INSERT INTO class_skill_proficiencies VALUES('cleric','History');
INSERT INTO class_skill_proficiencies VALUES('cleric','Insight');
INSERT INTO class_skill_proficiencies VALUES('cleric','Medicine');
INSERT INTO class_skill_proficiencies VALUES('cleric','Persuasion');
INSERT INTO class_skill_proficiencies VALUES('cleric','Religion');
INSERT INTO class_skill_proficiencies VALUES('paladin','Athletics');
INSERT INTO class_skill_proficiencies VALUES('paladin','Insight');
INSERT INTO class_skill_proficiencies VALUES('paladin','Intimidation');
INSERT INTO class_skill_proficiencies VALUES('paladin','Medicine');
INSERT INTO class_skill_proficiencies VALUES('paladin','Persuasion');
INSERT INTO class_skill_proficiencies VALUES('paladin','Religion');
INSERT INTO class_skill_proficiencies VALUES('rogue','Acrobatics');
INSERT INTO class_skill_proficiencies VALUES('rogue','Athletics');
INSERT INTO class_skill_proficiencies VALUES('rogue','Deception');
INSERT INTO class_skill_proficiencies VALUES('rogue','Insight');
INSERT INTO class_skill_proficiencies VALUES('rogue','Intimidation');
INSERT INTO class_skill_proficiencies VALUES('rogue','Investigation');
INSERT INTO class_skill_proficiencies VALUES('rogue','Perception');
INSERT INTO class_skill_proficiencies VALUES('rogue','Performance');
INSERT INTO class_skill_proficiencies VALUES('rogue','Persuasion');
INSERT INTO class_skill_proficiencies VALUES('rogue','Sleight of Hand');
INSERT INTO class_skill_proficiencies VALUES('rogue','Stealth');
INSERT INTO class_skill_proficiencies VALUES('rogue','Survival');
INSERT INTO class_skill_proficiencies VALUES('warlock','Arcana');
INSERT INTO class_skill_proficiencies VALUES('warlock','Deception');
INSERT INTO class_skill_proficiencies VALUES('warlock','History');
INSERT INTO class_skill_proficiencies VALUES('warlock','Intimidation');
INSERT INTO class_skill_proficiencies VALUES('warlock','Investigation');
INSERT INTO class_skill_proficiencies VALUES('warlock','Nature');
INSERT INTO class_skill_proficiencies VALUES('warlock','Religion');
INSERT INTO class_skill_proficiencies VALUES('wizard','Arcana');
INSERT INTO class_skill_proficiencies VALUES('wizard','History');
INSERT INTO class_skill_proficiencies VALUES('wizard','Insight');
INSERT INTO class_skill_proficiencies VALUES('wizard','Investigation');
INSERT INTO class_skill_proficiencies VALUES('wizard','Medicine');
INSERT INTO class_skill_proficiencies VALUES('wizard','Religion');
INSERT INTO encounter_dc VALUES(1,50,75,100);
INSERT INTO encounter_dc VALUES(2,100,150,200);
INSERT INTO encounter_dc VALUES(3,150,225,400);
INSERT INTO encounter_dc VALUES(4,250,375,500);
INSERT INTO encounter_dc VALUES(5,500,750,1100);
INSERT INTO encounter_dc VALUES(6,600,1000,1400);
INSERT INTO encounter_dc VALUES(7,750,1300,1700);
INSERT INTO encounter_dc VALUES(8,1000,1700,2100);
INSERT INTO encounter_dc VALUES(9,1300,2000,2600);
INSERT INTO encounter_dc VALUES(10,1600,2300,3100);
INSERT INTO encounter_dc VALUES(11,1900,2900,4100);
INSERT INTO encounter_dc VALUES(12,2200,3700,4700);
INSERT INTO encounter_dc VALUES(13,2600,4200,5400);
INSERT INTO encounter_dc VALUES(14,2900,4900,6200);
INSERT INTO encounter_dc VALUES(15,3300,5400,7800);
INSERT INTO encounter_dc VALUES(16,3800,6100,9800);
INSERT INTO encounter_dc VALUES(17,4500,7200,11700);
INSERT INTO encounter_dc VALUES(18,5000,8700,14200);
INSERT INTO encounter_dc VALUES(19,5500,10700,17200);
INSERT INTO encounter_dc VALUES(20,6400,13200,22000);
