-- TaleKeeper Game Data Export
-- Generated: 2025-09-13T13:48:22.560740
-- Tables: classes, races, feats, fighting_styles, levelup_costs, level_thresholds, campaigns, level_progression


-- classes (11 rows)
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('fighter', 'Fighter', 'A master of martial combat, skilled with a variety of weapons and armor.', 10, 'Strength or Dexterity', 2, '{"armor": "chain_mail", "weapons": ["shield"], "equipment": ["dungeoneer_pack", "javelin_2"]}', '[{"name": "Martial Weapon", "choice_type": "weapon", "options": ["longsword", "greatsword", "rapier"], "max_selections": 1, "is_required": true}, {"name": "Armor", "choice_type": "armor", "options": ["studded leather", "breastplate", "chain mail"], "max_selections": 1, "is_required": true}]', 0, 'simple weapons,martial weapons', 'light armor,medium armor,heavy armor,shields', '');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('barbarian', 'Barbarian', 'A fierce warrior of primitive background who can enter a battle rage.', 12, 'Strength', 2, '{}', '[]', 1, 'simple weapons,martial weapons', 'light armor,medium armor,shields', '');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('cleric', 'Cleric', 'A priestly champion who wields divine magic in service of a higher power.', 8, 'Wisdom', 2, '{}', '[]', 2, 'simple weapons', 'light armor,medium armor,shields', 'holy symbol,focus');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('paladin', 'Paladin', 'A holy warrior bound to a sacred oath, wielding divine magic.', 10, 'Strength and Charisma', 2, '{}', '[]', 3, 'simple weapons,martial weapons', 'light armor,medium armor,heavy armor,shields', 'holy symbol');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('rogue', 'Rogue', 'A scoundrel who uses stealth and trickery to overcome obstacles.', 8, 'Dexterity', 4, '{"armor": "leather_armor", "weapons": ["rapier", "shortbow"], "equipment": ["burglar_pack", "thieves_tools"]}', '[{"name": "Starting Equipment", "options": ["(A) Leather Armor, 2 Daggers, Shortsword, Shortbow, 20 Arrows, Quiver, Thieves Tools, Burglar Pack, 8 GP", "(B) Studded Leather Armor, 2 Shortswords, Thieves Tools, Burglar Pack, 15 GP", "(C) 100 GP"]}]', 4, 'simple weapons,hand crossbow,longsword,rapier,shortsword', 'light armor', '');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('warlock', 'Warlock', 'A wielder of magic derived from a bargain with an extraplanar entity.', 8, 'Charisma', 2, '{}', '[]', 5, 'simple weapons', 'light armor', 'rod,focus');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('wizard', 'Wizard', 'A scholarly magic-user capable of manipulating the structures of spellcasting.', 6, 'Intelligence', 2, '{}', '[]', 6, 'dagger,dart,sling,quarterstaff,light crossbow', '', 'wand,focus');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('sorcerer', 'Sorcerer', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'dagger,dart,sling,quarterstaff,light crossbow', '', 'focus');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('ranger', 'Ranger', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'simple weapons,martial weapons', 'light armor,medium armor,shields', '');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('druid', 'Druid', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'simple weapons', 'light armor,medium armor,shields', 'focus');
INSERT INTO classes (id, name, description, hit_die, primary_ability, skill_choices, starting_equipment, equipment_choices, display_order, weapon_proficiencies, armor_proficiencies, item_proficiencies) VALUES ('bard', 'Bard', NULL, NULL, NULL, NULL, NULL, NULL, 0, 'simple weapons', 'light armor', 'focus');

-- races (2 rows)
INSERT INTO races (id, name, description, size, speed, ability_score_increases, traits, languages, subraces, display_order) VALUES ('human', 'Human', 'Versatile and ambitious, humans are the most common race in most D&D worlds.', 'Medium', 30, '{}', '{"resourceful": "You gain Heroic Inspiration whenever you finish a Long Rest.", "skillful": "You gain proficiency in one skill of your choice.", "versatile": "You gain an Origin feat of your choice."}', '["Common"]', '[]', 0);
INSERT INTO races (id, name, description, size, speed, ability_score_increases, traits, languages, subraces, display_order) VALUES ('dwarf', 'Dwarf', 'Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.', 'Medium', 25, '{}', '{"darkvision": "You have Darkvision with a range of 120 feet.", "dwarven_resilience": "You have Resistance to Poison damage. You also have Advantage on saving throws you make to avoid or end the Poisoned condition.", "dwarven_toughness": "Your Hit Point maximum increases by 1, and it increases by 1 again whenever you gain a level."}', '["Common", "Dwarvish"]', '[]', 1);

-- feats (82 rows)
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('ability_score_improvement', 'Ability Score Improvement', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('actor', 'Actor', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('alert', 'Alert', 'You gain the following benefits: Initiative Proficiency - When you roll Initiative, you can add your Proficiency Bonus to the roll.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('archery', 'Archery', 'You gain a +2 bonus to attack rolls you make with ranged weapons.', '[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]', '{}', '{}', 'SRD', 'fighting_style');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('athlete', 'Athlete', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('blessed_warrior', 'Blessed Warrior', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('blind_fighting', 'Blind Fighting', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_combat_prowess', 'Boon of Combat Prowess', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_dimensional_travel', 'Boon of Dimensional Travel', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_energy_resistance', 'Boon of Energy Resistance', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_fate', 'Boon of Fate', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_fortitude', 'Boon of Fortitude', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_irresistible_offense', 'Boon of Irresistible Offense', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_recovery', 'Boon of Recovery', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_skill', 'Boon of Skill', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_speed', 'Boon of Speed', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_spell_recall', 'Boon of Spell Recall', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_truesight', 'Boon of Truesight', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('boon_of_the_night_spirit', 'Boon of the Night Spirit', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('charger', 'Charger', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('chef', 'Chef', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('crafter', 'Crafter', 'You are practiced in the crafting of one or more objects and the selling of those objects. You gain proficiency with three different artisan tools of your choice.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('crossbow_expert', 'Crossbow Expert', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('crusher', 'Crusher', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('defense', 'Defense', 'While you are wearing armor, you gain a +1 bonus to AC.', '[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]', '{}', '{}', 'SRD', 'fighting_style');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('defensive_duelist', 'Defensive Duelist', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('druidic_warrior', 'Druidic Warrior', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('dual_wielder', 'Dual Wielder', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('dueling', 'Dueling', 'When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.', '[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]', '{}', '{}', 'SRD', 'fighting_style');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('dungeon_delver', 'Dungeon Delver', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('durable', 'Durable', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('elemental_adept', 'Elemental Adept', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('fey-touched', 'Fey-Touched', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('grappler', 'Grappler', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('great_weapon_fighting', 'Great Weapon Fighting', 'When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll, even if the new roll is a 1 or a 2.', '[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]', '{}', '{}', 'SRD', 'fighting_style');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('great_weapon_master', 'Great Weapon Master', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('heavily_armored', 'Heavily Armored', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('heavy_armor_master', 'Heavy Armor Master', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('interception', 'Interception', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('keen_mind', 'Keen Mind', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('lightly_armored', 'Lightly Armored', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('linguist', 'Linguist', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('lucky', 'Lucky', 'You gain the following benefits: Luck Points - You have a number of Luck Points equal to your Proficiency Bonus and can spend the points on the benefits below. You regain your expended Luck Points when you finish a Long Rest. Advantage - When you roll a d20 for a D20 Test, you can spend 1 Luck Point to give yourself Advantage on the roll. Disadvantage - When a creature rolls a d20 for an attack roll against you, you can spend 1 Luck Point to impose Disadvantage on that roll.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('mage_slayer', 'Mage Slayer', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('martial_adept', 'Martial Adept', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('martial_weapon_training', 'Martial Weapon Training', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('medium_armor_master', 'Medium Armor Master', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('mobile', 'Mobile', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('moderately_armored', 'Moderately Armored', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('mounted_combatant', 'Mounted Combatant', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('musician', 'Musician', 'You gain the following benefits: Instrument Training - You gain proficiency with three Musical Instruments of your choice. Encouraging Song - As you finish a Short or Long Rest, you can play a song on a Musical Instrument with which you have proficiency and give Heroic Inspiration to allies who hear the song. The number of allies you can affect in this way equals your Proficiency Bonus.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('piercer', 'Piercer', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('poisoner', 'Poisoner', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('polearm_master', 'Polearm Master', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('protection', 'Protection', 'When a creature you can see attacks a target other than you that is within 5 feet of you, you can use your reaction to impose disadvantage on the attack roll. You must be wielding a shield.', '[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]', '{}', '{}', 'SRD', 'fighting_style');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('savage_attacker', 'Savage Attacker', 'You''ve trained to deal particularly damaging strikes. Once per turn when you hit a target with a weapon, you can roll the weapon''s damage dice twice and use either roll against the target.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('shadow-touched', 'Shadow-Touched', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('sharpshooter', 'Sharpshooter', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('shield_master', 'Shield Master', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('skill_expert', 'Skill Expert', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('skilled', 'Skilled', 'You have a knack for learning new things. You gain proficiency in any combination of three skills or tools of your choice.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('skulker', 'Skulker', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('slasher', 'Slasher', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('speedy', 'Speedy', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('spell_sniper', 'Spell Sniper', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('tavern_brawler', 'Tavern Brawler', 'You gain the following benefits: Enhanced Unarmed Strike - When you hit with your Unarmed Strike and deal damage, you can deal Bludgeoning damage equal to 1d4 plus your Strength modifier instead of the normal damage of an Unarmed Strike. Damage Rerolls - Whenever you roll a damage die for your Unarmed Strike, you can reroll the die if it rolls a 1, and you must use the new roll.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('thrown_weapon_fighting', 'Thrown Weapon Fighting', 'You can draw a weapon that has the thrown property as part of the attack you make with the weapon. In addition, when you hit with a ranged attack using a thrown weapon, you gain a +2 bonus to the damage roll.', '[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]', '{}', '{}', 'SRD', 'fighting_style');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('tough', 'Tough', 'Your Hit Point maximum increases by an amount equal to twice your character level when you gain this feat. Whenever you gain a character level thereafter, your Hit Point maximum increases by an additional 2 Hit Points.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('two-weapon_fighting', 'Two-Weapon Fighting', 'When you engage in two-weapon fighting, you can add your ability modifier to the damage of the second attack.', '[{"class": {"fighter": 1}}, {"class": {"paladin": 2}}]', '{}', '{}', 'SRD', 'fighting_style');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('unarmed_fighting', 'Unarmed Fighting', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('weapon_master', 'Weapon Master', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('magic_initiate_cleric', 'Magic Initiate (Cleric)', 'You have learned magical theory or been exposed to elemental forces. You learn spells from the Cleric class.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('magic_initiate_wizard', 'Magic Initiate (Wizard)', 'You have learned magical theory or been exposed to elemental forces. You learn spells from the Wizard class.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('healer', 'Healer', 'You gain the following benefits: Battle Medic - If you have a Healer''s Kit, you can expend one use of it and tend to a creature within 5 feet of yourself as a Utilize action. That creature can expend one of its Hit Point Dice, and you then roll that die. The creature regains a number of Hit Points equal to the roll plus your Proficiency Bonus. Healing Rerolls - Whenever you roll a die to determine the number of Hit Points you restore with a spell or with this feat''s Battle Medic benefit, you can reroll the die if it rolls a 1, and you must use the new roll.', '[]', '{}', '{}', 'SRD', 'O');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('inspiring_leader', 'Inspiring Leader', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('observant', 'Observant', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('resilient', 'Resilient', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('ritual_caster', 'Ritual Caster', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('sentinel', 'Sentinel', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('telekinetic', 'Telekinetic', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('telepathic', 'Telepathic', '', '[]', '{}', '{}', 'SRD', 'general');
INSERT INTO feats (id, name, description, prerequisites, ability_score_increases, benefits, source, category) VALUES ('war_caster', 'War Caster', '', '[]', '{}', '{}', 'SRD', 'general');

-- levelup_costs (4 rows)
INSERT INTO levelup_costs (id, level_range_start, level_range_end, training_days, training_cost_gp) VALUES (1, 2, 4, 10, 20);
INSERT INTO levelup_costs (id, level_range_start, level_range_end, training_days, training_cost_gp) VALUES (2, 5, 10, 20, 40);
INSERT INTO levelup_costs (id, level_range_start, level_range_end, training_days, training_cost_gp) VALUES (3, 11, 16, 30, 60);
INSERT INTO levelup_costs (id, level_range_start, level_range_end, training_days, training_cost_gp) VALUES (4, 17, 20, 40, 80);

-- campaigns (1 rows)
INSERT INTO campaigns (id, name, monster_type_weights, difficulty_distribution, rest_rules, style, available_classes, monster_alignment_rules) VALUES ('conan', 'Conan', '{"fiend": 0.2, "aberration": 0.1, "humanoid": 0.7}', '{"low": 0.5, "moderate": 0.4, "high": 0.1}', '{"wilderness_interrupt_chance": 0.1, "town_interrupt_chance": 0.5}', 'Harsh, grimdark sword & sorcery. Fiends and strange horrors abound; men are treacherous.', '["barbarian", "fighter", "rogue", "paladin", "cleric", "warlock", "wizard"]', '{"allow_evil": true, "allow_humanoid_not_good": true}');

-- level_progression (20 rows)
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (1, 0, 2);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (2, 300, 2);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (3, 900, 2);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (4, 2700, 2);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (5, 6500, 3);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (6, 14000, 3);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (7, 23000, 3);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (8, 34000, 3);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (9, 48000, 4);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (10, 64000, 4);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (11, 85000, 4);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (12, 100000, 4);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (13, 120000, 5);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (14, 140000, 5);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (15, 165000, 5);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (16, 195000, 5);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (17, 225000, 6);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (18, 265000, 6);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (19, 305000, 6);
INSERT INTO level_progression (level, experience_points, proficiency_bonus) VALUES (20, 355000, 6);
