INSERT INTO hazards (name, level_min, level_max, hazard_type, dc, save_type, damage_dice, damage_avg, damage_type, failure_effect, success_effect, mechanics, description, category, frequency) VALUES
('Green Slime', 1, 4, 'Nuisance', 10, 'Dexterity', '1d10', 5, 'Acid', '5 (1d10) Acid damage + ongoing', 'Avoid contact', 'Coverage: 5-foot square patches. Senses: Blindsight 30 feet. Movement: Drops from above when detecting movement; otherwise immobile. Initial Damage: 5 (1d10) Acid damage on contact. Ongoing Effect: Damage repeats at start of each turn until scraped off (action required). Material Damage: 11 (2d10) Acid damage per round to wood/metal; destroys nonmagical scrapers. Vulnerability: Destroyed by direct sunlight, Cold, Fire, or Radiant damage.', 'Acidic green slime devours flesh, organic material, and metal on contact. Bright green, wet, and sticky, it clings to walls, floors, and ceilings in patches.', 'standard', NULL),

('Poisonous Gas', 1, 4, 'Nuisance', 12, 'Constitution', '1d10', 5, 'Poison', '5 (1d10) Poison damage', 'Half damage', 'Coverage: Up to ten 10-foot Cubes. Replenishment: Continuous or periodic from natural/magical source. Dispersal: Strong wind clears for 1 minute. Additional Effect: Disadvantage on Death Saving Throws while in gas.', 'Poisonous gas is usually encountered in enclosed spaces like sewers or sealed tombs. The transparent gas carries a foul odor.', 'standard', NULL),

('Poisonous Gas', 5, 10, 'Nuisance', 14, 'Constitution', '2d10', 11, 'Poison', '11 (2d10) Poison damage', 'Half damage', 'Coverage: Up to ten 10-foot Cubes. Replenishment: Continuous or periodic from natural/magical source. Dispersal: Strong wind clears for 1 minute. Additional Effect: Disadvantage on Death Saving Throws while in gas.', 'Poisonous gas is usually encountered in enclosed spaces like sewers or sealed tombs. The transparent gas carries a foul odor.', 'standard', NULL),

('Poisonous Gas', 11, 16, 'Nuisance', 16, 'Constitution', '4d10', 22, 'Poison', '22 (4d10) Poison damage', 'Half damage', 'Coverage: Up to ten 10-foot Cubes. Replenishment: Continuous or periodic from natural/magical source. Dispersal: Strong wind clears for 1 minute. Additional Effect: Disadvantage on Death Saving Throws while in gas.', 'Poisonous gas is usually encountered in enclosed spaces like sewers or sealed tombs. The transparent gas carries a foul odor.', 'standard', NULL),

('Poisonous Gas', 17, 20, 'Nuisance', 18, 'Constitution', '10d10', 55, 'Poison', '55 (10d10) Poison damage', 'Half damage', 'Coverage: Up to ten 10-foot Cubes. Replenishment: Continuous or periodic from natural/magical source. Dispersal: Strong wind clears for 1 minute. Additional Effect: Disadvantage on Death Saving Throws while in gas.', 'Poisonous gas is usually encountered in enclosed spaces like sewers or sealed tombs. The transparent gas carries a foul odor.', 'standard', NULL),

('Quicksand Pit', 1, 4, 'Nuisance', 10, 'Strength (Athletics)', '1d4+1', 3, NULL, 'Restrained, sink 1d4 feet/turn', NULL, 'Dimensions: 10 feet deep, 10-foot square area. Initial Sink: 1d4 + 1 feet on entering. Condition: Restrained. Ongoing: Sinks 1d4 feet per turn. Escape: Action, Strength (Athletics) DC 10 + feet sunk. Full Submersion: Total Cover, Blinded, suffocation risk. Rescue: Action, Strength (Athletics) DC 5 + feet sunk.', 'Quicksand pit that restrains and pulls creatures down.', 'standard', NULL),

('Quicksand Pit', 5, 10, 'Nuisance', NULL, 'Strength (Athletics)', '1d6', 4, NULL, 'Restrained, sink 1d6 feet/turn (15 ft deep)', NULL, 'Dimensions: 15 feet deep, 10-foot square area. Ongoing: Sinks 1d6 feet per turn. Escape: Action, Strength (Athletics) DC 10 + feet sunk. Full Submersion: Total Cover, Blinded, suffocation risk. Rescue: Action, Strength (Athletics) DC 5 + feet sunk.', 'Deeper quicksand pit that restrains and pulls creatures down faster.', 'standard', NULL),

('Quicksand Pit', 11, 16, 'Nuisance', NULL, 'Strength (Athletics)', '1d8', 5, NULL, 'Restrained, sink 1d8 feet/turn (20 ft deep)', NULL, 'Dimensions: 20 feet deep, 10-foot square area. Ongoing: Sinks 1d8 feet per turn. Escape: Action, Strength (Athletics) DC 10 + feet sunk. Full Submersion: Total Cover, Blinded, suffocation risk. Rescue: Action, Strength (Athletics) DC 5 + feet sunk.', 'Deep quicksand pit that restrains and pulls creatures down rapidly.', 'standard', NULL),

('Quicksand Pit', 17, 20, 'Nuisance', NULL, 'Strength (Athletics)', '1d10', 6, NULL, 'Restrained, sink 1d10 feet/turn (30 ft deep)', NULL, 'Dimensions: 30 feet deep, 10-foot square area. Ongoing: Sinks 1d10 feet per turn. Escape: Action, Strength (Athletics) DC 10 + feet sunk. Full Submersion: Total Cover, Blinded, suffocation risk. Rescue: Action, Strength (Athletics) DC 5 + feet sunk.', 'Very deep quicksand pit that restrains and pulls creatures down very rapidly.', 'standard', NULL),

('Razorvine', 1, 4, 'Nuisance', 10, 'Dexterity', '1d10', 5, 'Slashing', '5 (1d10) Slashing damage', 'No damage', 'Wall/Hedge Stats: 10-foot high, 10-foot wide, 5-foot thick. AC: 11. HP: 25. Immunities: Bludgeoning, Piercing, Psychic damage.', 'Razorvine grows in wild tangles and hedges, clinging to buildings and surfaces like ivy.', 'standard', NULL),

('Rockslide', 1, 4, 'Deadly', 15, 'Dexterity', '2d10', 11, 'Bludgeoning', '11 (2d10) Bludgeoning, Prone, buried', 'Half damage only', 'Aftermath: Space becomes Difficult Terrain. Burial: Prone creatures gain Restrained and Total Cover. Escape: Action, DC 15 Strength (Athletics) check. Failed Escape: Remains buried, gains 1 Exhaustion level. Rescue: 1 minute to free another creature.', 'Cascading rocks and debris that can bury creatures.', 'standard', NULL),

('Rockslide', 5, 10, 'Deadly', 15, 'Dexterity', '4d10', 22, 'Bludgeoning', '22 (4d10) Bludgeoning, Prone, buried', 'Half damage only', 'Aftermath: Space becomes Difficult Terrain. Burial: Prone creatures gain Restrained and Total Cover. Escape: Action, DC 15 Strength (Athletics) check. Failed Escape: Remains buried, gains 1 Exhaustion level. Rescue: 1 minute to free another creature.', 'Heavy rockslide with more debris.', 'standard', NULL),

('Rockslide', 11, 16, 'Deadly', 15, 'Dexterity', '10d10', 55, 'Bludgeoning', '55 (10d10) Bludgeoning, Prone, buried', 'Half damage only', 'Aftermath: Space becomes Difficult Terrain. Burial: Prone creatures gain Restrained and Total Cover. Escape: Action, DC 15 Strength (Athletics) check. Failed Escape: Remains buried, gains 1 Exhaustion level. Rescue: 1 minute to free another creature.', 'Massive rockslide with extensive debris.', 'standard', NULL),

('Rockslide', 17, 20, 'Deadly', 15, 'Dexterity', '18d10', 99, 'Bludgeoning', '99 (18d10) Bludgeoning, Prone, buried', 'Half damage only', 'Aftermath: Space becomes Difficult Terrain. Burial: Prone creatures gain Restrained and Total Cover. Escape: Action, DC 15 Strength (Athletics) check. Failed Escape: Remains buried, gains 1 Exhaustion level. Rescue: 1 minute to free another creature.', 'Catastrophic rockslide that can crush even powerful creatures.', 'standard', NULL),

('Collapsing Roof', 1, 4, 'Deadly', 15, 'Dexterity', '3d10', 16, 'Bludgeoning', '16 (3d10) Bludgeoning, Prone, pinned', 'Half damage, move to nearest safe space', 'Aftermath: Space becomes Difficult Terrain. Pinned: Prone creatures gain Restrained and Total Cover. Escape: Action, DC 15 Strength (Athletics) check. Failed Escape: Remains pinned, gains 1 Exhaustion level. Rescue: 1 minute to free another creature.', 'Ceiling collapses, raining debris on creatures below.', 'standard', NULL),

('Collapsing Roof', 5, 10, 'Deadly', 15, 'Dexterity', '5d10', 27, 'Bludgeoning', '27 (5d10) Bludgeoning, Prone, pinned', 'Half damage, move to nearest safe space', 'Aftermath: Space becomes Difficult Terrain. Pinned: Prone creatures gain Restrained and Total Cover. Escape: Action, DC 15 Strength (Athletics) check. Failed Escape: Remains pinned, gains 1 Exhaustion level. Rescue: 1 minute to free another creature.', 'Heavy ceiling collapses with substantial debris.', 'standard', NULL),

('Collapsing Roof', 11, 16, 'Deadly', 16, 'Dexterity', '10d10', 55, 'Bludgeoning', '55 (10d10) Bludgeoning, Prone, pinned', 'Half damage, move to nearest safe space', 'Aftermath: Space becomes Difficult Terrain. Pinned: Prone creatures gain Restrained and Total Cover. Escape: Action, DC 16 Strength (Athletics) check. Failed Escape: Remains pinned, gains 1 Exhaustion level. Rescue: 1 minute to free another creature.', 'Massive ceiling collapse with tons of debris.', 'standard', NULL),

('Collapsing Roof', 17, 20, 'Deadly', 17, 'Dexterity', '16d10', 88, 'Bludgeoning', '88 (16d10) Bludgeoning, Prone, pinned', 'Half damage, move to nearest safe space', 'Aftermath: Space becomes Difficult Terrain. Pinned: Prone creatures gain Restrained and Total Cover. Escape: Action, DC 17 Strength (Athletics) check. Failed Escape: Remains pinned, gains 1 Exhaustion level. Rescue: 1 minute to free another creature.', 'Catastrophic ceiling collapse that can devastate powerful creatures.', 'standard', NULL),

('Vicious Vine', 1, 4, 'Nuisance', 12, 'Dexterity', '1d10', 5, 'Necrotic', 'Grappled (escape DC 12), 5 (1d10) Necrotic/turn', 'Avoid grapple', 'Stats: AC 11, HP 16. Immunities: Bludgeoning, Piercing, Psychic damage. Trigger: Within 5 feet on turn or starting turn there. Damage: 5 (1d10) Necrotic per turn while grappled. Capacity: One creature at a time. Special: DC 10 Charisma (Persuasion) with Speak with Plants for release.', 'Magically animated vines that appear as ordinary plants until they move.', 'standard', NULL),

('Vicious Vine', 5, 10, 'Nuisance', 14, 'Dexterity', '2d10', 11, 'Necrotic', 'Grappled (escape DC 14), 11 (2d10) Necrotic/turn', 'Avoid grapple', 'Stats: AC 11, HP 16. Immunities: Bludgeoning, Piercing, Psychic damage. Trigger: Within 5 feet on turn or starting turn there. Damage: 11 (2d10) Necrotic per turn while grappled. Capacity: One creature at a time. Special: DC 10 Charisma (Persuasion) with Speak with Plants for release.', 'Stronger magically animated vines with life-draining properties.', 'standard', NULL),

('Vicious Vine', 11, 16, 'Nuisance', 16, 'Dexterity', '4d10', 22, 'Necrotic', 'Grappled (escape DC 16), 22 (4d10) Necrotic/turn', 'Avoid grapple', 'Stats: AC 11, HP 16. Immunities: Bludgeoning, Piercing, Psychic damage. Trigger: Within 5 feet on turn or starting turn there. Damage: 22 (4d10) Necrotic per turn while grappled. Capacity: One creature at a time. Special: DC 10 Charisma (Persuasion) with Speak with Plants for release.', 'Powerful magically animated vines with potent life-draining properties.', 'standard', NULL),

('Vicious Vine', 17, 20, 'Nuisance', 18, 'Dexterity', '10d10', 55, 'Necrotic', 'Grappled (escape DC 18), 55 (10d10) Necrotic/turn', 'Avoid grapple', 'Stats: AC 11, HP 16. Immunities: Bludgeoning, Piercing, Psychic damage. Trigger: Within 5 feet on turn or starting turn there. Damage: 55 (10d10) Necrotic per turn while grappled. Capacity: One creature at a time. Special: DC 10 Charisma (Persuasion) with Speak with Plants for release.', 'Extremely powerful magically animated vines that can drain life from even legendary creatures.', 'standard', NULL),

('Webs', 1, 4, 'Nuisance', 12, 'Dexterity', NULL, NULL, NULL, 'Restrained (escape DC 12)', 'Avoid restrain', 'Terrain: Difficult Terrain in web-filled areas. Escape: Action, DC 12 Strength (Athletics) or Dexterity (Acrobatics). Web Stats (per 10-foot Cube): AC: 10, HP: 15, Vulnerability: Fire damage, Immunities: Piercing, Poison, Psychic damage.', 'Giant spider webs that create Difficult Terrain and ensnare prey.', 'standard', NULL),

('Yellow Mold', 1, 4, 'Deadly', 15, 'Constitution', '2d10', 11, 'Poison', '11 (2d10) Poison + Poisoned, 5 (1d10)/turn', 'No effect', 'Coverage: 5-foot square patches. Trigger: Touch releases spore cloud (10-foot Cube). Ongoing: 5 (1d10) Poison damage per turn while Poisoned. Recovery: Save at end of each turn to end effect. Vulnerability: Destroyed by direct sunlight or any Fire damage.', 'Yellow mold grows in dark places and releases toxic spores when disturbed.', 'standard', NULL),

('Yellow Mold', 5, 10, 'Nuisance', 15, 'Constitution', '2d10', 11, 'Poison', '11 (2d10) Poison + Poisoned, 5 (1d10)/turn', 'No effect', 'Coverage: 5-foot square patches. Trigger: Touch releases spore cloud (10-foot Cube). Ongoing: 5 (1d10) Poison damage per turn while Poisoned. Recovery: Save at end of each turn to end effect. Vulnerability: Destroyed by direct sunlight or any Fire damage.', 'Yellow mold grows in dark places and releases toxic spores when disturbed.', 'standard', NULL),

('River Styx', 11, 16, 'Nuisance', 20, 'Intelligence', '3d12', 19, 'Psychic', '19 (3d12) Psychic + memory loss', 'No effect', 'Trigger: Drinking, entering, or starting turn in river. Duration: 30 days (no spells or Magic action). Immunity: Affected creatures can swim/drink without additional effects. Removal: Greater Restoration, Heal, or Wish only. Permanent Effect: After 30 days, total memory loss (Wish or divine intervention required). Water Potency: Loses effect after 24 hours unless preserved by special rituals.', 'The River Styx courses through the Lower Planes, shattering intellect and stripping memories.', 'standard', NULL),

('Inferno', 5, 10, 'Deadly', NULL, NULL, '4d10', 22, 'Fire', '22 (4d10) Fire + burning condition', NULL, 'Minimum Size: Four contiguous 10-foot Cubes. Suppression: Each 10-foot Cube requires 10 gallons of water. Growth: Strong wind for 1 minute adds 1d4 new Cubes. Duration: Burns out after 1d10 minutes without fuel. Object Damage: 22 (4d10) Fire damage immediately and at end of each minute (non-worn/carried items). Creature Damage: 22 (4d10) Fire damage on entering or starting turn within.', 'When an uncontrolled fire spreads, it can create an inferno that quickly engulfs creatures, objects, and vegetation.', 'standard', NULL),

('Inferno', 11, 16, 'Nuisance', NULL, NULL, '4d10', 22, 'Fire', '22 (4d10) Fire + burning condition', NULL, 'Minimum Size: Four contiguous 10-foot Cubes. Suppression: Each 10-foot Cube requires 10 gallons of water. Growth: Strong wind for 1 minute adds 1d4 new Cubes. Duration: Burns out after 1d10 minutes without fuel. Object Damage: 22 (4d10) Fire damage immediately and at end of each minute (non-worn/carried items). Creature Damage: 22 (4d10) Fire damage on entering or starting turn within.', 'When an uncontrolled fire spreads, it can create an inferno that quickly engulfs creatures, objects, and vegetation.', 'standard', NULL),

('Deep Water', 1, 20, 'Environmental', 10, 'Constitution', NULL, NULL, NULL, '1 Exhaustion level', NULL, 'Swimming through deep water (more than 100 feet deep) presents additional challenges because of the water''s pressure and cold temperature. After each hour of swimming in deep water, a creature that lacks a Swim Speed must succeed on a DC 10 Constitution saving throw or gain 1 Exhaustion level.', 'Deep water pressure and cold temperature.', 'environmental', 'Each hour'),

('Extreme Cold', 1, 20, 'Environmental', 10, 'Constitution', NULL, NULL, NULL, '1 Exhaustion level', NULL, 'When the temperature is 0 degrees Fahrenheit or lower, a creature exposed to the extreme cold must succeed on a DC 10 Constitution saving throw at the end of each hour or gain 1 Exhaustion level. Creatures that have Resistance or Immunity to Cold damage automatically succeed on the save.', 'Temperature is 0 degrees Fahrenheit or lower.', 'environmental', 'Each hour'),

('Extreme Heat', 1, 20, 'Environmental', 5, 'Constitution', NULL, NULL, NULL, '1 Exhaustion level', NULL, 'When the temperature is 100 degrees Fahrenheit or higher, a creature exposed to the extreme heat and without access to drinkable water must succeed on a Constitution saving throw at the end of each hour or gain 1 Exhaustion level. The DC is 5 for the first hour and increases by 1 for each additional hour. Creatures wearing Medium or Heavy armor have Disadvantage on the save. Creatures that have Resistance or Immunity to Fire damage automatically succeed on the save.', 'Temperature is 100 degrees Fahrenheit or higher without drinkable water.', 'environmental', 'Each hour (DC +1/hour)'),

('Frigid Water', 1, 20, 'Environmental', 10, 'Constitution', NULL, NULL, NULL, '1 Exhaustion level', NULL, 'A creature can be immersed in frigid water for a number of minutes equal to its Constitution score before suffering any ill effects. Each additional minute spent in frigid water requires the creature to succeed on a DC 10 Constitution saving throw or gain 1 Exhaustion level. Creatures with Resistance or Immunity to Cold damage automatically succeed on the save, as do creatures that are naturally adapted to living in ice-cold water.', 'Ice-cold water immersion.', 'environmental', 'After Con score minutes');