-- TaleKeeper Game Data Export
-- Generated: 2025-09-13T13:48:22.573748
-- Tables: subclasses, subclass_features, class_features, barbarian_features, fighter_features, cleric_features, rogue_features, warlock_features, wizard_features


-- subclasses (15 rows)
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('thief', 'rogue', 'Thief', 'A master of stealth and larceny with fast hands', 'You hone your skills in the larcenous arts, learning tricks to enhance your agility and stealth.', 3, '2025-09-12 07:46:32');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('assassin', 'rogue', 'Assassin', 'A deadly killer who strikes from the shadows', 'You focus your training on the grim art of death, becoming a master of poison, disguise, and stealth.', 3, '2025-09-12 07:46:32');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('champion', 'fighter', 'Champion', 'A master of martial combat, skilled with a variety of weapons and armor', 'The archetypal Champion focuses on the development of raw physical power honed to deadly perfection.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('battle_master', 'fighter', 'Battle Master', 'Those who employ martial techniques passed down through generations', 'Battle Masters are students of combat, utilizing maneuvers and tactics to control the battlefield.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('eldritch_knight', 'fighter', 'Eldritch Knight', 'Fighters who combine martial mastery with careful study of magic', 'Eldritch Knights use magical techniques similar to those practiced by wizards, blending martial might and magic.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('berserker', 'barbarian', 'Path of the Berserker', 'For barbarians, rage is a means to an end—that end being violence', 'Berserkers channel their rage into brutal melee attacks, becoming unstoppable forces of destruction.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('totem_warrior', 'barbarian', 'Path of the Totem Warrior', 'Barbarians who accept a spirit animal as guide, protector, and inspiration', 'Totem Warriors draw strength from the spirits of animals, gaining their attributes in battle.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('arcane_trickster', 'rogue', 'Arcane Trickster', 'Rogues who enhance their skills with magic, learning wizard spells', 'Arcane Tricksters use enchantment and illusion magic to enhance their natural stealth and agility.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('evocation', 'wizard', 'School of Evocation', 'Wizards who focus on magic that creates powerful elemental effects', 'Evokers harness destructive magical energy, sculpting spells to protect allies while devastating foes.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('abjuration', 'wizard', 'School of Abjuration', 'Wizards specializing in protective magic and wards', 'Abjurers are masters of protective magic, creating powerful wards and barriers against harm.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('divination', 'wizard', 'School of Divination', 'Wizards who peer through time and fate to uncover secrets', 'Diviners can glimpse the future and use this knowledge to alter fate itself.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('life', 'cleric', 'Life Domain', 'Clerics who focus on healing and preserving life', 'Life domain clerics are blessed with powerful healing magic, mending wounds and restoring vitality.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('light', 'cleric', 'Light Domain', 'Clerics who wield the power of light and fire', 'Light domain clerics channel divine radiance to banish darkness and incinerate foes.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('war', 'cleric', 'War Domain', 'Clerics who bless warriors and inspire victory in battle', 'War domain clerics are blessed crusaders, channeling divine might in combat.', 3, '2025-09-13 01:12:47');
INSERT INTO subclasses (id, class_id, name, description, flavor_text, selection_level, created_at) VALUES ('gladiator', 'fighter', 'Gladiator', 'A crowd-pleasing arena warrior who thrives on spectacle', 'Gladiators are showmen as much as warriors, turning combat into performance art.', 3, '2025-09-12 17:14:45');

-- subclass_features (22 rows)
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (1, 'champion', 3, 'Improved Critical', 'Your weapon attacks score a critical hit on a roll of 19 or 20', '{"critical_range_min": 19}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (2, 'champion', 7, 'Remarkable Athlete', 'Add half proficiency (round up) to STR, DEX, and CON checks without proficiency', '{"half_prof_physical": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (3, 'champion', 10, 'Additional Fighting Style', 'Choose a second Fighting Style', '{"additional_fighting_style": 1}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (4, 'champion', 10, 'Heroic Warrior', 'At start of turn, regain 5 + CON mod HP if below half HP', '{"regen_hp": "5+con"}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (5, 'champion', 15, 'Superior Critical', 'Your weapon attacks score a critical hit on a roll of 18-20', '{"critical_range_min": 18}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (6, 'champion', 18, 'Survivor', 'At start of turn, regain 10 + CON mod HP if below half HP', '{"regen_hp": "10+con"}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (7, 'gladiator', 3, 'Crowd Pleaser', 'When you score a critical hit, gain temp HP equal to your fighter level', '{"on_crit": "temp_hp_level"}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (8, 'gladiator', 3, 'Performance Fighter', 'Gain proficiency in Performance and Intimidation', '{"skills": ["performance", "intimidation"]}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (9, 'gladiator', 7, 'Arena Reflexes', 'You have advantage on initiative rolls and can draw/stow two weapons as part of your movement', '{"initiative_advantage": true, "quick_draw": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (10, 'gladiator', 10, 'Signature Move', 'Once per short rest, make a special attack that deals extra damage and can frighten', '{"damage_bonus": "2d6", "save_dc": "8+prof+str", "effect": "frightened"}', 'action', 1, 'short', '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (11, 'gladiator', 15, 'Crowd Favorite', 'When below half HP, gain resistance to all damage except psychic', '{"bloodied_resistance": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (12, 'gladiator', 18, 'Champion of the Arena', 'Your Signature Move recharges on a 5-6 on d6 at start of turn', '{"signature_recharge": "5-6"}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (13, 'thief', 3, 'Fast Hands', 'Use thieves tools, Use Object action, or Sleight of Hand as bonus action', '{"bonus_action_options": ["thieves_tools", "use_object", "sleight_of_hand"]}', 'bonus_action', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (14, 'thief', 3, 'Second-Story Work', 'Climb at normal speed, running jump bonus equals DEX mod', '{"climb_speed": "normal", "jump_bonus": "dex"}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (15, 'thief', 9, 'Supreme Sneak', 'Advantage on Stealth checks if you move no more than half speed', '{"stealth_advantage_half_speed": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (16, 'thief', 13, 'Use Magic Device', 'Ignore class, race, and level requirements on magic items', '{"ignore_magic_requirements": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (17, 'thief', 17, 'Thief''s Reflexes', 'Take two turns in first round of combat (at initiative and initiative-10)', '{"double_first_turn": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (18, 'assassin', 3, 'Assassinate', 'Advantage on attacks vs creatures that haven''t acted; hits on surprised creatures are crits', '{"advantage_vs_slow": true, "auto_crit_surprised": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (19, 'assassin', 3, 'Assassin''s Tools', 'Gain proficiency with poisoner''s kit and disguise kit', '{"tool_proficiencies": ["poisoners_kit", "disguise_kit"]}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (20, 'assassin', 9, 'Infiltration Expertise', 'Create false identities with 7 days and 25gp', '{"create_identity": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (21, 'assassin', 13, 'Impostor', 'Perfectly mimic speech, writing, and behavior after 3 hours study', '{"perfect_mimicry": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');
INSERT INTO subclass_features (id, subclass_id, level, feature_name, description, mechanics, action_type, uses_per_rest, rest_type, created_at) VALUES (22, 'assassin', 17, 'Death Strike', 'When you hit a surprised creature, force CON save or double damage', '{"death_strike_dc": "8+prof+dex", "double_damage_on_fail": true}', 'passive', NULL, NULL, '2025-09-12 07:46:32');

-- barbarian_features (3 rows)
INSERT INTO barbarian_features (character_id, level, rage_uses_current, rage_uses_max, rage_damage_bonus, is_raging, rage_turns_remaining, unarmored_defense_active, reckless_attack_available, danger_sense_active) VALUES ('test_barbarian_1', 3, 3, 3, 2, 0, 0, 1, 1, 1);
INSERT INTO barbarian_features (character_id, level, rage_uses_current, rage_uses_max, rage_damage_bonus, is_raging, rage_turns_remaining, unarmored_defense_active, reckless_attack_available, danger_sense_active) VALUES ('df138df2-5f3a-4922-a615-9bf8854b5eff', 1, 0, 2, 2, 0, 0, 1, 0, 0);
INSERT INTO barbarian_features (character_id, level, rage_uses_current, rage_uses_max, rage_damage_bonus, is_raging, rage_turns_remaining, unarmored_defense_active, reckless_attack_available, danger_sense_active) VALUES ('a79e70e9-18e9-4df5-a1f2-ff088c26ab74', 1, 0, 2, 2, 0, 0, 1, 0, 0);

-- fighter_features (16 rows)
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('81b2ab47-dcfb-4913-841e-6d5c8850e98d', 1, NULL, 1, 1, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('16238700-5fee-4eae-9ad7-70b9c6591b68', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('cacaa6ce-0703-4bc3-a3fb-15ad3e87862a', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('8445da69-8ba9-4abf-970d-5d125f5a093d', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('ce213370-99a9-47c7-bc32-451559b8d6ef', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('57c4e763-160d-40ec-aeaf-551ec06d7acb', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('075264ba-cd46-4925-b00d-543d045d8ce6', 1, NULL, 1, 1, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('4dc95a73-89c6-42ca-93a3-4ce168089ad2', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('c11f2026-7d9a-43b8-9414-dc3a28192117', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('ed535bcd-3108-4000-8494-38f114845447', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('b2f013c3-9c42-481c-ad20-12cb4a9abb24', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 1, NULL, 1, 1, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('55281b4a-814f-452b-920c-ad1b87c57f0a', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('85fcece0-8b74-4407-b27b-60a013a20b61', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
INSERT INTO fighter_features (character_id, level, fighting_style, action_surge_uses_current, action_surge_uses_max, second_wind_used, indomitable_uses_current, indomitable_uses_max, extra_attacks, weapon_masteries_known) VALUES ('54de2b31-6fc8-4127-8a47-a9c10f493a2e', 1, NULL, 0, 0, 0, 0, 0, 1, 3);
