-- Uncategorized tables
-- Generated: 2025-09-13T13:47:34.392952


-- background_proficiencies (33 rows)
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('soldier', 'skill', 'Athletics');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('soldier', 'skill', 'Intimidation');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('soldier', 'tool', 'gaming_set');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('soldier', 'tool', 'vehicles_land');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('criminal', 'skill', 'Deception');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('criminal', 'skill', 'Stealth');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('criminal', 'tool', 'thieves_tools');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('criminal', 'tool', 'gaming_set');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('sage', 'skill', 'Arcana');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('sage', 'skill', 'History');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('sage', 'language', 'choice_2');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('acolyte', 'skill', 'Insight');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('acolyte', 'skill', 'Religion');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('acolyte', 'language', 'choice_2');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('criminal', 'skill', 'Deception');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('criminal', 'skill', 'Stealth');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('criminal', 'tool', 'thieves_tools');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('criminal', 'tool', 'gaming_set');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('folk_hero', 'skill', 'Animal Handling');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('folk_hero', 'skill', 'Survival');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('folk_hero', 'tool', 'artisan_tools');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('folk_hero', 'tool', 'vehicles_land');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('noble', 'skill', 'History');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('noble', 'skill', 'Persuasion');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('noble', 'tool', 'gaming_set');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('noble', 'language', 'choice_1');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('sage', 'skill', 'Arcana');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('sage', 'skill', 'History');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('sage', 'language', 'choice_2');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('soldier', 'skill', 'Athletics');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('soldier', 'skill', 'Intimidation');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('soldier', 'tool', 'gaming_set');
INSERT INTO background_proficiencies (background_id, proficiency_type, proficiency_name) VALUES ('soldier', 'tool', 'vehicles_land');

-- backgrounds (5 rows)
INSERT INTO backgrounds (id, name, description, skill_proficiencies, language_proficiencies, tool_proficiencies, starting_equipment, equipment_option_a, equipment_option_a_gold, feature_name, feature_description, feat, display_order) VALUES ('farmer', 'Farmer', 'You know the hard work of the farm and field. You understand the cycle of seasons and the patience required to nurture crops and livestock.', '["Animal Handling", "Nature"]', '[]', '["Carpenter''s Tools"]', '{"option_a": {"equipment": ["carpenters_tools", "shovel", "common_clothes", "belt_pouch", "backpack", "potion_of_healing", "rations_5"], "gold": 10}, "option_b": {"gold": 50}}', '["carpenters_tools", "shovel", "common_clothes", "belt_pouch", "backpack", "potion_of_healing", "rations_5"]', 10, '', '', 'Tough', 0);
INSERT INTO backgrounds (id, name, description, skill_proficiencies, language_proficiencies, tool_proficiencies, starting_equipment, equipment_option_a, equipment_option_a_gold, feature_name, feature_description, feat, display_order) VALUES ('soldier', 'Soldier', 'You began training for war as soon as you reached adulthood and carry precious few memories of life before you took up arms. Battle is in your blood. The crash of weapons, the stink of blood, the screams of enemies—this is the music that makes your heart race. War has been your life for as long as you care to remember.', '["Athletics", "Intimidation"]', '[]', '["Gaming Set"]', '{"option_a": {"equipment": ["spear", "shortbow", "arrows_20", "gaming_set", "healers_kit", "quiver", "travelers_clothes"], "gold": 14}, "option_b": {"gold": 50}}', '["spear", "shortbow", "arrows_20", "gaming_set", "healers_kit", "quiver", "travelers_clothes"]', 14, '', '', 'Savage Attacker', 1);
INSERT INTO backgrounds (id, name, description, skill_proficiencies, language_proficiencies, tool_proficiencies, starting_equipment, equipment_option_a, equipment_option_a_gold, feature_name, feature_description, feat, display_order) VALUES ('acolyte', 'Acolyte', 'You devoted yourself to service in a temple, either nestled in a town or secluded in a sacred grove. There you performed rites in honor of a god or pantheon. You served under a priest and studied religion. Thanks to your priest''s instruction and your own devotion, you gained mastery over your god''s mysteries.', '["Insight", "Religion"]', '[]', '["Calligrapher''s Supplies"]', '{"option_a": {"equipment": ["calligraphers_supplies", "prayer_book", "holy_symbol", "parchment_10", "robe"], "gold": 8}, "option_b": {"gold": 50}}', '["calligraphers_supplies", "prayer_book", "holy_symbol", "parchment_10", "robe"]', 8, '', '', 'Magic Initiate (Cleric)', 2);
INSERT INTO backgrounds (id, name, description, skill_proficiencies, language_proficiencies, tool_proficiencies, starting_equipment, equipment_option_a, equipment_option_a_gold, feature_name, feature_description, feat, display_order) VALUES ('criminal', 'Criminal', 'You once broke the law and paid for it, learning a hard lesson about the reach of legal authority. You spent time among other criminals and developed connections within the criminal underworld. You''re far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization.', '["Sleight of Hand", "Stealth"]', '[]', '["Thieves'' Tools"]', '{"option_a": {"equipment": ["dagger", "dagger", "thieves_tools", "crowbar", "pouch", "pouch", "travelers_clothes"], "gold": 16}, "option_b": {"gold": 50}}', '["dagger", "dagger", "thieves_tools", "crowbar", "pouch", "pouch", "travelers_clothes"]', 16, '', '', 'Alert', 3);
INSERT INTO backgrounds (id, name, description, skill_proficiencies, language_proficiencies, tool_proficiencies, starting_equipment, equipment_option_a, equipment_option_a_gold, feature_name, feature_description, feat, display_order) VALUES ('sage', 'Sage', 'You spent your formative years traveling between libraries, scriptoriums, and universities, learning from scholars, wizards, and other learned persons. You became an apprentice to a master who taught you to value knowledge above all else. You mastered the basics of accessing the most fundamental sources of knowledge.', '["Arcana", "History"]', '[]', '["Calligrapher''s Supplies"]', '{"option_a": {"equipment": ["quarterstaff", "calligraphers_supplies", "history_book", "parchment_8", "robe"], "gold": 8}, "option_b": {"gold": 50}}', '["quarterstaff", "calligraphers_supplies", "history_book", "parchment_8", "robe"]', 8, '', '', 'Magic Initiate (Wizard)', 4);

-- barbarian_features (3 rows)
INSERT INTO barbarian_features (character_id, level, rage_uses_current, rage_uses_max, rage_damage_bonus, is_raging, rage_turns_remaining, unarmored_defense_active, reckless_attack_available, danger_sense_active) VALUES ('test_barbarian_1', 3, 3, 3, 2, 0, 0, 1, 1, 1);
INSERT INTO barbarian_features (character_id, level, rage_uses_current, rage_uses_max, rage_damage_bonus, is_raging, rage_turns_remaining, unarmored_defense_active, reckless_attack_available, danger_sense_active) VALUES ('df138df2-5f3a-4922-a615-9bf8854b5eff', 1, 0, 2, 2, 0, 0, 1, 0, 0);
INSERT INTO barbarian_features (character_id, level, rage_uses_current, rage_uses_max, rage_damage_bonus, is_raging, rage_turns_remaining, unarmored_defense_active, reckless_attack_available, danger_sense_active) VALUES ('a79e70e9-18e9-4df5-a1f2-ff088c26ab74', 1, 0, 2, 2, 0, 0, 1, 0, 0);

-- character_combat_state (25 rows)
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('test_fighter_manual', NULL, 0, 0, 0, 0, 20, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('63357a69-68a5-4410-9d20-ece328306222', NULL, 0, 0, 0, 0, 20, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('81b2ab47-dcfb-4913-841e-6d5c8850e98d', NULL, 0, 0, 0, 0, 20, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('test-fighter-123', NULL, 0, 0, 0, 0, 20, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('e4c07d78-d3b1-497c-8330-66a952221b04', NULL, 0, 0, 0, 0, 20, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('d02c96f7-1146-4bbf-b358-afb5620d6736', NULL, 0, 0, 0, 0, 20, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('576527f5-cd92-4f7b-a8cc-39cb6d3a8887', NULL, 0, 0, 0, 0, 20, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('a03e6fea-6fc4-4910-9895-b19ec88e674d', NULL, 0, 0, 0, 0, 19, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('5241ba0b-9184-4240-8941-0de699dcc540', NULL, 0, 0, 0, 0, 19, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('c3e59f0b-8d87-4c0c-a443-27b1c2a312a7', NULL, 0, 0, 0, 0, 19, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('0c918916-f259-423c-9fb8-7a23055a6c91', NULL, 0, 0, 0, 0, 19, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('b7ad1dd0-f286-4702-8cc5-0180ceb4bb69', NULL, 0, 0, 0, 0, 18, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('9b00c022-86a0-4d29-975c-f455df2143f9', NULL, 0, 0, 0, 0, 18, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('f2826a8d-ec86-4131-bd99-ecbed9437acf', NULL, 0, 0, 0, 0, 18, '2025-09-06 16:08:41');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('16238700-5fee-4eae-9ad7-70b9c6591b68', NULL, 0, 0, 0, 0, 20, '2025-09-07 08:02:01');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('ce213370-99a9-47c7-bc32-451559b8d6ef', NULL, 0, 0, 0, 0, 20, '2025-09-07 08:50:04');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('075264ba-cd46-4925-b00d-543d045d8ce6', NULL, 0, 0, 0, 0, 20, '2025-09-07 12:51:15');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('4dc95a73-89c6-42ca-93a3-4ce168089ad2', NULL, 0, 0, 0, 0, 20, '2025-09-09 04:34:09');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('c044f0b4-b994-4c0f-b142-b41f6b69d7e0', NULL, 0, 0, 0, 0, 20, '2025-09-09 04:37:14');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('b2f013c3-9c42-481c-ad20-12cb4a9abb24', NULL, 0, 0, 0, 0, 20, '2025-09-09 04:43:00');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('00cfe148-40c5-4b8d-940b-b1222c5d6d0e', NULL, 0, 0, 0, 0, 19, '2025-09-09 07:13:44');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('55281b4a-814f-452b-920c-ad1b87c57f0a', NULL, 0, 0, 0, 0, 20, '2025-09-09 12:08:16');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('fighter-test-001', NULL, 0, 0, 0, 0, 20, '2025-09-12 16:11:58');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('grimfar-001', NULL, 0, 0, 0, 0, 20, '2025-09-12 17:47:45');
INSERT INTO character_combat_state (character_id, studied_target_id, last_miss_turn, heroic_warrior_active, survivor_active, last_attack_missed, critical_range_min, updated_at) VALUES ('54de2b31-6fc8-4127-8a47-a9c10f493a2e', NULL, 0, 0, 0, 0, 20, '2025-09-13 04:10:13');

-- character_feats (41 rows)
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (39, '81b2ab47-dcfb-4913-841e-6d5c8850e98d', 'Tough', 'character_creation', 1, '2025-09-03 13:28:48');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (40, '81b2ab47-dcfb-4913-841e-6d5c8850e98d', 'Alert', 'character_creation', 1, '2025-09-03 13:28:48');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (41, '81b2ab47-dcfb-4913-841e-6d5c8850e98d', 'Great Weapon Fighting', 'character_creation', 1, '2025-09-03 13:28:48');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (60, 'test-fighter-123', 'Savage Attacker', 'background', 1, '2025-09-04 03:45:30');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (61, 'test-fighter-123', 'Great Weapon Fighting', 'class', 1, '2025-09-04 03:45:30');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (76, 'df138df2-5f3a-4922-a615-9bf8854b5eff', 'Tough', 'character_creation', 1, '2025-09-04 14:36:56');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (83, '16238700-5fee-4eae-9ad7-70b9c6591b68', 'Tough', 'character_creation', 1, '2025-09-07 07:59:36');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (84, '16238700-5fee-4eae-9ad7-70b9c6591b68', 'Savage Attacker', 'character_creation', 1, '2025-09-07 07:59:36');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (85, '16238700-5fee-4eae-9ad7-70b9c6591b68', 'Defense', 'character_creation', 1, '2025-09-07 07:59:36');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (94, 'cacaa6ce-0703-4bc3-a3fb-15ad3e87862a', 'Great Weapon Fighting', 'character_creation', 1, '2025-09-07 08:08:31');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (95, '8445da69-8ba9-4abf-970d-5d125f5a093d', 'Savage Attacker', 'character_creation', 1, '2025-09-07 08:42:55');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (96, '8445da69-8ba9-4abf-970d-5d125f5a093d', 'Tough', 'character_creation', 1, '2025-09-07 08:42:55');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (97, '8445da69-8ba9-4abf-970d-5d125f5a093d', 'Defense', 'character_creation', 1, '2025-09-07 08:42:55');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (98, 'ce213370-99a9-47c7-bc32-451559b8d6ef', 'Savage Attacker', 'character_creation', 1, '2025-09-07 08:48:07');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (99, 'ce213370-99a9-47c7-bc32-451559b8d6ef', 'Tough', 'character_creation', 1, '2025-09-07 08:48:07');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (100, 'ce213370-99a9-47c7-bc32-451559b8d6ef', 'Defense', 'character_creation', 1, '2025-09-07 08:48:07');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (101, '57c4e763-160d-40ec-aeaf-551ec06d7acb', 'Archery', 'character_creation', 1, '2025-09-07 10:39:50');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (102, 'a79e70e9-18e9-4df5-a1f2-ff088c26ab74', 'Savage Attacker', 'character_creation', 1, '2025-09-07 10:42:30');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (103, 'a79e70e9-18e9-4df5-a1f2-ff088c26ab74', 'Tough', 'character_creation', 1, '2025-09-07 10:42:30');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (104, '075264ba-cd46-4925-b00d-543d045d8ce6', 'Alert', 'character_creation', 1, '2025-09-07 12:48:15');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (105, '075264ba-cd46-4925-b00d-543d045d8ce6', 'Tough', 'character_creation', 1, '2025-09-07 12:48:15');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (106, '075264ba-cd46-4925-b00d-543d045d8ce6', 'Great Weapon Fighting', 'character_creation', 1, '2025-09-07 12:48:15');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (107, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'Savage Attacker', 'character_creation', 1, '2025-09-09 04:27:38');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (108, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'Tough', 'character_creation', 1, '2025-09-09 04:27:38');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (109, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'Defense', 'character_creation', 1, '2025-09-09 04:27:38');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (112, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'Savage Attacker', 'character_creation', 1, '2025-09-09 04:34:52');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (113, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'Tough', 'character_creation', 1, '2025-09-09 04:34:52');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (114, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'Defense', 'character_creation', 1, '2025-09-09 04:34:52');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (115, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'Tough', 'character_creation', 1, '2025-09-09 04:42:45');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (116, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'Dueling', 'character_creation', 1, '2025-09-09 04:42:45');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (117, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'Tough', 'character_creation', 1, '2025-09-09 05:42:12');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (118, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'Savage Attacker', 'character_creation', 1, '2025-09-09 05:42:12');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (119, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'Defense', 'character_creation', 1, '2025-09-09 05:42:12');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (120, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'Tough', 'character_creation', 1, '2025-09-09 12:06:31');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (121, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'Skilled', 'character_creation', 1, '2025-09-09 12:06:31');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (122, '85fcece0-8b74-4407-b27b-60a013a20b61', 'Savage Attacker', 'character_creation', 1, '2025-09-12 17:47:17');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (123, '85fcece0-8b74-4407-b27b-60a013a20b61', 'Tough', 'character_creation', 1, '2025-09-12 17:47:17');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (124, '85fcece0-8b74-4407-b27b-60a013a20b61', 'Two-Weapon Fighting', 'character_creation', 1, '2025-09-12 17:47:17');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (125, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'Savage Attacker', 'character_creation', 1, '2025-09-12 17:49:49');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (126, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'Tough', 'character_creation', 1, '2025-09-12 17:49:49');
INSERT INTO character_feats (id, character_id, feat_name, feat_source, level_acquired, created_at) VALUES (127, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'Two-Weapon Fighting', 'character_creation', 1, '2025-09-12 17:49:49');

-- character_proficiencies (107 rows)
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (3, 'test-fighter-123', 'weapon', 'Simple weapons', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (4, 'test-fighter-123', 'weapon', 'Martial weapons', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (5, 'test-fighter-123', 'armor', 'Light armor', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (6, 'test-fighter-123', 'armor', 'Medium armor', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (7, 'test-fighter-123', 'armor', 'Heavy armor', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (8, 'test-fighter-123', 'armor', 'Shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (230, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (231, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'weapon', 'martial', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (232, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (233, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'armor', 'medium', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (234, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'armor', 'heavy', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (235, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'armor', 'shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (244, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'saving_throw', 'strength', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (245, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'saving_throw', 'constitution', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (246, '075264ba-cd46-4925-b00d-543d045d8ce6', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (247, '075264ba-cd46-4925-b00d-543d045d8ce6', 'weapon', 'martial', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (248, '075264ba-cd46-4925-b00d-543d045d8ce6', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (249, '075264ba-cd46-4925-b00d-543d045d8ce6', 'armor', 'medium', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (250, '075264ba-cd46-4925-b00d-543d045d8ce6', 'armor', 'heavy', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (251, '075264ba-cd46-4925-b00d-543d045d8ce6', 'armor', 'shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (260, '075264ba-cd46-4925-b00d-543d045d8ce6', 'saving_throw', 'strength', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (261, '075264ba-cd46-4925-b00d-543d045d8ce6', 'saving_throw', 'constitution', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (262, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (263, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'weapon', 'martial', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (264, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (265, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'armor', 'medium', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (266, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'armor', 'heavy', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (267, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'armor', 'shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (276, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'saving_throw', 'strength', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (277, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'saving_throw', 'constitution', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (278, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (279, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'weapon', 'martial', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (280, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (281, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'armor', 'medium', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (282, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'armor', 'heavy', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (283, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'armor', 'shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (292, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'saving_throw', 'strength', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (293, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'saving_throw', 'constitution', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (308, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (309, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'weapon', 'hand_crossbow', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (310, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'weapon', 'longsword', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (311, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'weapon', 'rapier', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (312, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'weapon', 'shortsword', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (313, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (318, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'skill', 'Deception', 'background');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (320, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'tool', 'thieves_tools', 'background');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (321, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'tool', 'gaming_set', 'background');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (322, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'saving_throw', 'dexterity', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (323, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'saving_throw', 'intelligence', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (324, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'skill', 'Insight', 'species');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (325, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'skill', 'Arcana', 'feat');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (326, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'skill', 'Medicine', 'feat');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (327, '98ae9e6b-20c9-4cd0-a94d-8185ed9ec7b1', 'skill', 'Survival', 'feat');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (347, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (348, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'weapon', 'martial', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (349, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (350, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'armor', 'medium', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (351, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'armor', 'heavy', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (352, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'armor', 'shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (353, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'skill', 'Intimidation', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (354, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'skill', 'Perception', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (355, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'skill', 'Athletics', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (356, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'saving_throw', 'strength', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (357, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'saving_throw', 'constitution', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (358, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (359, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'weapon', 'martial', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (360, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (361, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'armor', 'medium', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (362, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'armor', 'heavy', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (363, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'armor', 'shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (364, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'skill', 'Athletics', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (365, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'skill', 'Perception', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (366, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'saving_throw', 'strength', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (367, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'saving_throw', 'constitution', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (368, 'grimfar-001', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (369, 'grimfar-001', 'weapon', 'martial', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (370, 'grimfar-001', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (371, 'grimfar-001', 'armor', 'medium', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (372, 'grimfar-001', 'armor', 'heavy', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (373, 'grimfar-001', 'armor', 'shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (374, 'grimfar-001', 'skill', 'Intimidation', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (375, 'grimfar-001', 'skill', 'Perception', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (376, 'grimfar-001', 'skill', 'Athletics', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (377, 'grimfar-001', 'saving_throw', 'strength', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (378, 'grimfar-001', 'saving_throw', 'constitution', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (379, '85fcece0-8b74-4407-b27b-60a013a20b61', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (380, '85fcece0-8b74-4407-b27b-60a013a20b61', 'weapon', 'martial', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (381, '85fcece0-8b74-4407-b27b-60a013a20b61', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (382, '85fcece0-8b74-4407-b27b-60a013a20b61', 'armor', 'medium', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (383, '85fcece0-8b74-4407-b27b-60a013a20b61', 'armor', 'heavy', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (384, '85fcece0-8b74-4407-b27b-60a013a20b61', 'armor', 'shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (385, '85fcece0-8b74-4407-b27b-60a013a20b61', 'skill', 'Acrobatics', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (386, '85fcece0-8b74-4407-b27b-60a013a20b61', 'skill', 'Athletics', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (387, '85fcece0-8b74-4407-b27b-60a013a20b61', 'skill', 'Perception', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (388, '85fcece0-8b74-4407-b27b-60a013a20b61', 'saving_throw', 'strength', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (389, '85fcece0-8b74-4407-b27b-60a013a20b61', 'saving_throw', 'constitution', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (390, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'weapon', 'simple', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (391, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'weapon', 'martial', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (392, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'armor', 'light', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (393, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'armor', 'medium', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (394, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'armor', 'heavy', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (395, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'armor', 'shields', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (396, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'skill', 'Insight', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (397, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'skill', 'Perception', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (398, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'skill', 'Athletics', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (399, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'saving_throw', 'strength', 'class');
INSERT INTO character_proficiencies (id, character_id, proficiency_type, proficiency_name, source) VALUES (400, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'saving_throw', 'constitution', 'class');

-- character_resources (31 rows)
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (1, '576527f5-cd92-4f7b-a8cc-39cb6d3a8887', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-06 16:51:23');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (2, '576527f5-cd92-4f7b-a8cc-39cb6d3a8887', 'Action Surge', 1, 1, 'short_rest', 'fighter', 2, '2025-09-06 16:51:23');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (3, 'a03e6fea-6fc4-4910-9895-b19ec88e674d', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-06 16:53:13');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (4, 'a03e6fea-6fc4-4910-9895-b19ec88e674d', 'Action Surge', 1, 1, 'short_rest', 'fighter', 2, '2025-09-06 16:53:13');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (5, '16238700-5fee-4eae-9ad7-70b9c6591b68', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-07 08:09:51');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (6, 'cacaa6ce-0703-4bc3-a3fb-15ad3e87862a', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-07 08:17:59');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (7, 'df138df2-5f3a-4922-a615-9bf8854b5eff', 'Rage', 2, 2, 'long_rest', 'barbarian', 1, '2025-09-07 08:18:00');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (8, 'ce213370-99a9-47c7-bc32-451559b8d6ef', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-07 08:48:13');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (9, 'test_barbarian_1', 'Rage', 3, 3, 'long_rest', 'barbarian', 1, '2025-09-07 10:38:11');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (10, '57c4e763-160d-40ec-aeaf-551ec06d7acb', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-07 10:39:56');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (11, 'a79e70e9-18e9-4df5-a1f2-ff088c26ab74', 'Rage', 2, 2, 'long_rest', 'barbarian', 1, '2025-09-07 10:42:36');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (14, '8445da69-8ba9-4abf-970d-5d125f5a093d', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-07 12:20:26');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (15, '63357a69-68a5-4410-9d20-ece328306222', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-07 12:20:26');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (16, '63357a69-68a5-4410-9d20-ece328306222', 'Action Surge', 1, 1, 'short_rest', 'fighter', 2, '2025-09-07 12:20:26');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (17, '81b2ab47-dcfb-4913-841e-6d5c8850e98d', 'Second Wind', 1, 2, 'short_rest', 'fighter', 1, '2025-09-07 12:24:57');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (18, '81b2ab47-dcfb-4913-841e-6d5c8850e98d', 'Action Surge', 0, 1, 'short_rest', 'fighter', 2, '2025-09-07 12:24:57');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (28, '075264ba-cd46-4925-b00d-543d045d8ce6', 'Second Wind', 3, 3, 'short_rest', 'fighter', 1, '2025-09-07 14:17:00');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (29, '075264ba-cd46-4925-b00d-543d045d8ce6', 'Action Surge', 1, 1, 'short_rest', 'fighter', 2, '2025-09-07 14:17:00');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (30, '4dc95a73-89c6-42ca-93a3-4ce168089ad2', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-09 04:27:50');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (31, 'c11f2026-7d9a-43b8-9414-dc3a28192117', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-09 04:32:07');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (32, 'ed535bcd-3108-4000-8494-38f114845447', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-09 04:33:20');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (33, 'c044f0b4-b994-4c0f-b142-b41f6b69d7e0', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-09 04:34:58');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (34, 'b2f013c3-9c42-481c-ad20-12cb4a9abb24', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-09 04:42:51');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (38, '55281b4a-814f-452b-920c-ad1b87c57f0a', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-09 12:06:37');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (67, 'fighter-test-001', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-12 17:35:03');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (68, 'fighter-test-001', 'Action Surge', 1, 1, 'short_rest', 'fighter', 2, '2025-09-12 17:35:03');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (69, 'grimfar-001', 'Action Surge', 1, 1, 'short_rest', 'fighter', 2, '2025-09-12 17:38:56');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (70, 'grimfar-001', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-12 17:38:56');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (71, '54de2b31-6fc8-4127-8a47-a9c10f493a2e', 'Second Wind', 2, 2, 'short_rest', 'fighter', 1, '2025-09-12 17:49:55');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (74, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'Second Wind', 3, 3, 'short_rest', 'fighter', 1, '2025-09-13 05:10:09');
INSERT INTO character_resources (id, character_id, resource_name, current_uses, max_uses, rest_type, source_class, source_level, created_at) VALUES (75, '00cfe148-40c5-4b8d-940b-b1222c5d6d0e', 'Action Surge', 1, 1, 'short_rest', 'fighter', 2, '2025-09-13 05:10:09');

-- character_weapon_masteries (1 rows)
INSERT INTO character_weapon_masteries (id, character_id, weapon_name, mastery_type) VALUES (1, 'test-fighter-123', 'Greatsword', 'Graze');

-- class_armor_proficiencies (16 rows)
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('fighter', 'light');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('fighter', 'medium');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('fighter', 'heavy');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('fighter', 'shields');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('barbarian', 'light');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('barbarian', 'medium');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('barbarian', 'shields');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('cleric', 'light');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('cleric', 'medium');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('cleric', 'shields');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('paladin', 'light');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('paladin', 'medium');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('paladin', 'heavy');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('paladin', 'shields');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('rogue', 'light');
INSERT INTO class_armor_proficiencies (class_id, armor_type) VALUES ('warlock', 'light');

-- class_equipment_choices (10 rows)
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (3, 'barbarian', 'weapon_choice', 'Weapon Choice', '["Shield + Spear", "Greataxe", "2x Scimitars"]', '2025-09-02 13:33:05');
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (4, 'barbarian', 'armor_choice', 'Armor/Helmet Choice', '["Dread Helm", "Scale Mail", "Chain Mail"]', '2025-09-02 13:33:05');
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (5, 'rogue', 'armor_choice', 'Armor', '["Studded Leather"]', '2025-09-02 13:33:05');
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (6, 'rogue', 'weapon_choice', 'Weapon Choice', '["Rapier + Dagger", "Scimitar + Shortsword", "2 Shortswords"]', '2025-09-02 13:33:05');
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (7, 'cleric', 'equipment_choice', 'Equipment', '["Holy Symbol + Scale Mail + Mace + Shield", "Holy Symbol + Chain Mail + Mace + Shield"]', '2025-09-02 13:33:13');
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (8, 'paladin', 'equipment_choice', 'Equipment Choice', '["Holy Symbol + Scale Mail + Longsword + Shield", "Holy Symbol + Chain Mail + Longsword + Shield", "Holy Symbol + Scale Mail + Greatsword", "Holy Symbol + Chain Mail + Greatsword"]', '2025-09-02 13:33:13');
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (9, 'wizard', 'equipment_choice', 'Equipment Choice', '["Arcane Focus + Spellbook + Quarterstaff", "Arcane Focus + Spellbook + Dagger"]', '2025-09-02 13:33:13');
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (10, 'warlock', 'equipment_auto', 'Starting Equipment', '["Studded Leather + Arcane Focus + Spear"]', '2025-09-02 13:33:20');
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (11, 'fighter', 'armor_choice', 'Armor Choice', '["Studded Leather", "Scale Mail", "Chain Mail"]', '2025-09-04 02:45:31');
INSERT INTO class_equipment_choices (id, class_id, choice_group, choice_name, options, created_at) VALUES (12, 'fighter', 'weapon_choice', 'Weapon Choice', '["Greatsword", "Longsword + Shield", "Scimitar + Scimitar"]', '2025-09-04 02:45:31');

-- class_saving_throws (14 rows)
INSERT INTO class_saving_throws (class_id, ability) VALUES ('fighter', 'strength');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('fighter', 'constitution');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('barbarian', 'strength');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('barbarian', 'constitution');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('cleric', 'wisdom');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('cleric', 'charisma');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('paladin', 'wisdom');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('paladin', 'charisma');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('rogue', 'dexterity');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('rogue', 'intelligence');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('warlock', 'wisdom');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('warlock', 'charisma');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('wizard', 'intelligence');
INSERT INTO class_saving_throws (class_id, ability) VALUES ('wizard', 'wisdom');

-- class_skill_choices (12 rows)
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('fighter', 2, '["Acrobatics", "Animal Handling", "Athletics", "History", "Insight", "Intimidation", "Perception", "Survival"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('barbarian', 2, '["Animal Handling", "Athletics", "Intimidation", "Nature", "Perception", "Survival"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('cleric', 2, '["History", "Insight", "Medicine", "Persuasion", "Religion"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('rogue', 4, '["Acrobatics", "Athletics", "Deception", "Insight", "Intimidation", "Investigation", "Perception", "Performance", "Persuasion", "Sleight of Hand", "Stealth"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('wizard', 2, '["Arcana", "History", "Insight", "Investigation", "Medicine", "Religion"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('paladin', 2, '["Athletics", "Insight", "Intimidation", "Medicine", "Persuasion", "Religion"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('fighter', 2, '["Acrobatics", "Animal Handling", "Athletics", "History", "Insight", "Intimidation", "Perception", "Survival"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('barbarian', 2, '["Animal Handling", "Athletics", "Intimidation", "Nature", "Perception", "Survival"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('cleric', 2, '["History", "Insight", "Medicine", "Persuasion", "Religion"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('rogue', 4, '["Acrobatics", "Athletics", "Deception", "Insight", "Intimidation", "Investigation", "Perception", "Performance", "Persuasion", "Sleight of Hand", "Stealth"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('wizard', 2, '["Arcana", "History", "Insight", "Investigation", "Medicine", "Religion"]');
INSERT INTO class_skill_choices (class_id, skill_count, available_skills) VALUES ('paladin', 2, '["Athletics", "Insight", "Intimidation", "Medicine", "Persuasion", "Religion"]');

-- class_skill_proficiencies (50 rows)
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('fighter', 'Acrobatics');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('fighter', 'Animal Handling');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('fighter', 'Athletics');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('fighter', 'History');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('fighter', 'Insight');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('fighter', 'Intimidation');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('fighter', 'Perception');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('fighter', 'Survival');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('barbarian', 'Animal Handling');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('barbarian', 'Athletics');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('barbarian', 'Intimidation');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('barbarian', 'Nature');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('barbarian', 'Perception');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('barbarian', 'Survival');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('cleric', 'History');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('cleric', 'Insight');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('cleric', 'Medicine');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('cleric', 'Persuasion');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('cleric', 'Religion');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('paladin', 'Athletics');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('paladin', 'Insight');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('paladin', 'Intimidation');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('paladin', 'Medicine');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('paladin', 'Persuasion');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('paladin', 'Religion');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Acrobatics');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Athletics');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Deception');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Insight');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Intimidation');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Investigation');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Perception');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Performance');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Persuasion');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Sleight of Hand');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Stealth');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('rogue', 'Survival');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('warlock', 'Arcana');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('warlock', 'Deception');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('warlock', 'History');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('warlock', 'Intimidation');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('warlock', 'Investigation');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('warlock', 'Nature');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('warlock', 'Religion');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('wizard', 'Arcana');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('wizard', 'History');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('wizard', 'Insight');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('wizard', 'Investigation');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('wizard', 'Medicine');
INSERT INTO class_skill_proficiencies (class_id, skill) VALUES ('wizard', 'Religion');

-- class_weapon_proficiencies (18 rows)
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('fighter', 'simple');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('fighter', 'martial');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('barbarian', 'simple');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('barbarian', 'martial');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('cleric', 'simple');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('paladin', 'simple');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('paladin', 'martial');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('rogue', 'simple');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('rogue', 'hand_crossbow');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('rogue', 'longsword');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('rogue', 'rapier');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('rogue', 'shortsword');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('warlock', 'simple');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('wizard', 'daggers');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('wizard', 'darts');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('wizard', 'slings');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('wizard', 'quarterstaffs');
INSERT INTO class_weapon_proficiencies (class_id, weapon_type) VALUES ('wizard', 'light crossbows');
