-- Migration 033: Add Missing Warlock Spells
-- Adds 54 spells that exist in spell_class_lists but not in spells table
-- Extracted from D&D 2024 SRD

INSERT INTO spells (id, name, level, school, casting_time, range_value, components, duration, description, concentration, ritual, classes)
VALUES
-- Level 2 Spells
('darkness', 'Darkness', 2, 'Evocation', 'Action', '60 feet', 'V, M (bat fur and a piece of coal)', 'Concentration, up to 10 minutes', 'For the duration, magical Darkness spreads from a point within range and fills a 15-foot-radius Sphere. Darkvision can''t see through it, and nonmagical light can''t illuminate it. Alternatively, you cast the spell on an object that isn''t being worn or carried, causing the Darkness to fill a 15-foot Emanation originating from that object. Covering that object with something opaque, such as a bowl or helm, blocks the Darkness. If any of this spell''s area overlaps with an area of Bright Light or Dim Light created by a spell of level 2 or lower, that other spell is dispelled.', 1, 0, '["sorcerer", "warlock", "wizard"]'),

('enthrall', 'Enthrall', 2, 'Enchantment', 'Action', '60 feet', 'V, S', 'Concentration, up to 1 minute', 'You weave a distracting string of words, causing creatures of your choice that you can see within range to make a Wisdom saving throw. Any creature you or your companions are fighting automatically succeeds on this save. On a failed save, a target has a -10 penalty to Wisdom (Perception) checks and Passive Perception until the spell ends.', 1, 0, '["bard", "warlock"]'),

('hold_person', 'Hold Person', 2, 'Enchantment', 'Action', '60 feet', 'V, S, M (a straight piece of iron)', 'Concentration, up to 1 minute', 'One Humanoid you can see within range must succeed on a Wisdom saving throw or have the Paralyzed condition for the duration. At the end of each of its turns, the target repeats the save, ending the spell on itself on a success. Using a Higher-Level Spell Slot. You can target one additional creature for each spell slot level above 2.', 1, 0, '["bard", "cleric", "druid", "sorcerer", "warlock", "wizard"]'),

('invisibility', 'Invisibility', 2, 'Illusion', 'Action', 'Touch', 'V, S, M (an eyelash in gum arabic)', 'Concentration, up to 1 hour', 'A creature you touch has the Invisible condition until the spell ends. The spell ends early immediately after the target makes an attack roll, deals damage, or casts a spell. Using a Higher-Level Spell Slot. You can target one additional creature for each spell slot level above 2.', 1, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

('mind_spike', 'Mind Spike', 2, 'Divination', 'Action', '60 feet', 'S', 'Concentration, up to 1 hour', 'You magically detect the presence of thinking creatures you can''t see. On your turn, you can use a Bonus Action to detect the direction to the nearest thinking creature within 30 feet of you. You know its distance from you and general direction but not its exact location. The creature doesn''t need to be moving to be detected, and hidden and invisible creatures are detected as well. The spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.', 1, 0, '["sorcerer", "warlock", "wizard"]'),

('mirror_image', 'Mirror Image', 2, 'Illusion', 'Action', 'Self', 'V, S', '1 minute', 'Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions, shifting position so it''s impossible to track which image is real. Each time a creature hits you with an attack roll during the spell''s duration, roll a d6 for each of your remaining duplicates. If any of the d6s rolls a 3 or higher, one of the duplicates is hit instead of you, and the duplicate is destroyed. The duplicates have your AC and use your saving throws. If an attack hits a duplicate, the duplicate is destroyed. A duplicate can be destroyed only by an attack that hits it. The spell ends when all three duplicates are destroyed. A creature is unaffected by this spell if it has the Blinded condition, Blindsight, or Truesight.', 0, 0, '["sorcerer", "warlock", "wizard"]'),

('misty_step', 'Misty Step', 2, 'Conjuration', 'Bonus Action', 'Self', 'V', 'Instantaneous', 'You teleport up to 30 feet to an unoccupied space that you can see. You can bring along objects if their weight doesn''t exceed what you can carry.', 0, 0, '["sorcerer", "warlock", "wizard"]'),

('ray_of_enfeeblement', 'Ray of Enfeeblement', 2, 'Necromancy', 'Action', '60 feet', 'V, S', 'Concentration, up to 1 minute', 'A beam of enervating energy shoots from you toward a creature within range. The target must make a Constitution saving throw. On a failed save, the target has Disadvantage on Strength-based D20 Tests for the duration. On each of its turns, it repeats the save, ending the spell on itself on a success.', 1, 0, '["warlock", "wizard"]'),

('spider_climb', 'Spider Climb', 2, 'Transmutation', 'Action', 'Touch', 'V, S, M (a drop of bitumen and a spider)', 'Concentration, up to 1 hour', 'Until the spell ends, one willing creature you touch gains the ability to move up, down, and across vertical surfaces and along ceilings, while leaving its hands free. The target also gains a Climb Speed equal to its Speed.', 1, 0, '["sorcerer", "warlock", "wizard"]'),

('suggestion', 'Suggestion', 2, 'Enchantment', 'Action', '30 feet', 'V, M (a drop of honey)', 'Concentration, up to 8 hours', 'You suggest a course of activity—described in no more than 25 words—to one creature you can see within range that can hear and understand you. The suggestion must sound achievable and not involve anything that would obviously deal damage to the target or its allies. For example, you could say, "Fetch the key to the cult''s treasure vault, and give the key to me." Or you could say, "Stop fighting, leave this library peacefully, and don''t come back." The target must succeed on a Wisdom saving throw or have the Charmed condition for the duration or until you or your allies deal damage to the target. The Charmed target pursues the suggestion to the best of its ability. The suggested activity can continue for the entire duration, but if the suggested activity can be completed in a shorter time, the spell ends early.', 1, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

-- Level 3 Spells
('fear', 'Fear', 3, 'Illusion', 'Action', 'Self', 'V, S, M (a white feather)', 'Concentration, up to 1 minute', 'Each creature in a 30-foot Cone must succeed on a Wisdom saving throw or drop whatever it is holding and have the Frightened condition for the duration. A Frightened creature takes the Dash action and moves away from you by the safest route on each of its turns unless there is nowhere to move. If the creature ends its turn in a space where it doesn''t have line of sight to you, the creature makes a Wisdom saving throw. On a successful save, the spell ends on that creature.', 1, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

('fly', 'Fly', 3, 'Transmutation', 'Action', 'Touch', 'V, S, M (a feather)', 'Concentration, up to 10 minutes', 'You touch a willing creature. For the duration, the target gains a Fly Speed of 60 feet and can hover. When the spell ends, the target falls if it is still aloft unless it can stop the fall. Using a Higher-Level Spell Slot. You can target one additional creature for each spell slot level above 3.', 1, 0, '["sorcerer", "warlock", "wizard"]'),

('gaseous_form', 'Gaseous Form', 3, 'Transmutation', 'Action', 'Touch', 'V, S, M (a bit of gauze)', 'Concentration, up to 1 hour', 'You transform a willing creature you touch, along with everything it''s wearing and carrying, into a misty cloud for the duration. The spell ends early if the creature drops to 0 Hit Points. While in this form, the target has a Fly Speed of 10 feet, can hover, and can enter and pass through spaces without squeezing. In addition, the target has Resistance to all damage except Force damage, and it has Advantage on Strength, Dexterity, and Constitution saving throws. The target can''t pick up or drop anything, attack, cast spells, or talk.', 1, 0, '["sorcerer", "warlock", "wizard"]'),

('hypnotic_pattern', 'Hypnotic Pattern', 3, 'Illusion', 'Action', '120 feet', 'S, M (a pinch of confetti)', 'Concentration, up to 1 minute', 'You create a twisting pattern of colors in a 30-foot Cube within range. The pattern appears for a moment and vanishes. Each creature in the area who can see the pattern must succeed on a Wisdom saving throw or have the Charmed condition for the duration. While Charmed, the creature has the Incapacitated condition and a Speed of 0. The spell ends on an affected creature if it takes any damage or if someone else uses an action to shake the creature out of its stupor.', 1, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

('major_image', 'Major Image', 3, 'Illusion', 'Action', '120 feet', 'V, S, M (a bit of fleece)', 'Concentration, up to 10 minutes', 'You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 20-foot Cube. The image appears at a spot that you can see within range and lasts for the duration. It seems real, including sounds, smells, and temperature appropriate to the thing depicted, but it can''t deal damage or cause conditions. If you are within range of the illusion, you can take a Magic action to cause the image to move to any other spot within range. As the image changes location, you can alter its appearance so that its movements appear natural for the image. Physical interaction with the image reveals it to be an illusion, for things can pass through it. A creature that takes a Study action to examine the image can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the creature can see through the image, and its other sensory qualities become faint to the creature. Using a Higher-Level Spell Slot. The spell lasts until dispelled, without requiring Concentration, if cast with a level 4+ spell slot.', 1, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

('tongues', 'Tongues', 3, 'Divination', 'Action', 'Touch', 'V, M (a miniature ziggurat)', '1 hour', 'This spell grants the creature you touch the ability to understand any spoken or signed language that it hears or sees. Moreover, when the target speaks or signs, any creature that knows at least one language can understand it if that creature can hear the speech or see the signing.', 0, 0, '["bard", "cleric", "sorcerer", "warlock", "wizard"]'),

('vampiric_touch', 'Vampiric Touch', 3, 'Necromancy', 'Action', 'Self', 'V, S', 'Concentration, up to 1 minute', 'The touch of your shadow-wreathed hand can siphon life force from others to heal your wounds. Make a melee spell attack against one creature within reach. On a hit, the target takes 3d6 Necrotic damage, and you regain Hit Points equal to half the amount of Necrotic damage dealt. On each of your later turns, you can take a Magic action to repeat the attack. Using a Higher-Level Spell Slot. The damage increases by 1d6 for each spell slot level above 3.', 1, 0, '["warlock", "wizard"]'),

-- Level 4 Spells
('blight', 'Blight', 4, 'Necromancy', 'Action', '30 feet', 'V, S', 'Instantaneous', 'A creature that you can see within range makes a Constitution saving throw, taking 8d8 Necrotic damage on a failed save or half as much damage on a successful one. A Plant creature automatically fails the save. Alternatively, target a nonmagical plant that isn''t a creature, such as a tree or shrub. It doesn''t make a save; it simply withers and dies. Using a Higher-Level Spell Slot. The damage increases by 1d8 for each spell slot level above 4.', 0, 0, '["druid", "sorcerer", "warlock", "wizard"]'),

('charm_monster', 'Charm Monster', 4, 'Enchantment', 'Action', '30 feet', 'V, S', '1 hour', 'One creature you can see within range makes a Wisdom saving throw. It does so with Advantage if you or your allies are fighting it. On a failed save, the target has the Charmed condition until the spell ends or until you or your allies damage it. The Charmed creature is Friendly to you. When the spell ends, the target knows it was Charmed by you. Using a Higher-Level Spell Slot. You can target one additional creature for each spell slot level above 4.', 0, 0, '["bard", "druid", "sorcerer", "warlock", "wizard"]'),

('dimension_door', 'Dimension Door', 4, 'Conjuration', 'Action', '500 feet', 'V', 'Instantaneous', 'You teleport to a location within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction, such as "200 feet straight downward" or "300 feet upward to the northwest at a 45-degree angle." You can also teleport one willing creature. The creature must be within 5 feet of you when you teleport, and it teleports to a space within 5 feet of your destination space. If you, the other creature, or both would arrive in a space occupied by a creature or completely filled by one or more objects, you and any creature traveling with you each take 4d6 Force damage, and the teleportation fails.', 0, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

('fire_shield', 'Fire Shield', 4, 'Evocation', 'Action', 'Self', 'V, S, M (a bit of phosphorus or a firefly)', '10 minutes', 'Wispy flames wreathe your body for the duration, shedding Bright Light in a 10-foot radius and Dim Light for an additional 10 feet. The flames provide you with a warm shield or a chill shield, as you choose. The warm shield grants you Resistance to Cold damage, and the chill shield grants you Resistance to Fire damage. In addition, whenever a creature within 5 feet of you hits you with a melee attack roll, the shield erupts with flame. The attacker takes 2d8 Fire damage from a warm shield or 2d8 Cold damage from a chill shield.', 0, 0, '["druid", "sorcerer", "wizard"]'),

('hallucinatory_terrain', 'Hallucinatory Terrain', 4, 'Illusion', '10 minutes', '300 feet', 'V, S, M (a mushroom and a green leaf)', '24 hours', 'You make natural terrain in a 150-foot Cube in range look, sound, and smell like another sort of natural terrain. Thus, open fields or a road can be made to resemble a swamp, hill, crevasse, or some other difficult or impassable terrain. A pond can be made to seem like a grassy meadow, a precipice like a gentle slope, or a rock-strewn gully like a wide and smooth road. Manufactured structures, equipment, and creatures within the area aren''t changed. The tactile characteristics of the terrain are unchanged, so creatures entering the area are likely to notice the illusion. If the difference isn''t obvious by touch, a creature examining the illusion can take a Study action to make an Intelligence (Investigation) check against your spell save DC to disbelieve it. On a successful check, the creature sees the illusion for what it is.', 1, 0, '["bard", "druid", "warlock", "wizard"]'),

-- Level 5 Spells
('contact_other_plane', 'Contact Other Plane', 5, 'Divination', '1 minute or Ritual', 'Self', 'V', '1 minute', 'You mentally contact a demigod, the spirit of a long-dead sage, or some other knowledgeable entity from another plane. Contacting this otherworldly intelligence can break your mind. When you cast this spell, make a DC 15 Intelligence saving throw. On a successful save, you can ask the entity up to five questions. You must ask your questions before the spell ends. The GM answers each question with one word, such as "yes," "no," "maybe," "never," "irrelevant," or "unclear" (if the entity doesn''t know the answer to the question). If a one-word answer would be misleading, the GM might instead offer a short phrase as an answer. On a failed save, you take 6d6 Psychic damage and have the Incapacitated condition until you finish a Long Rest. A Greater Restoration spell cast on you ends this effect.', 0, 1, '["warlock", "wizard"]'),

('dream', 'Dream', 5, 'Illusion', '1 minute', 'Special', 'V, S, M (a handful of sand)', '8 hours', 'You target a creature you know on the same plane of existence. You or a willing creature you touch enters a trance state to act as a dream messenger. While in the trance, the messenger is Incapacitated and has a Speed of 0. If the target is asleep, the messenger appears in the target''s dreams and can converse with the target as long as it remains asleep, through the spell''s duration. The messenger can also shape the dream''s environment, creating landscapes, objects, and other images. The messenger can emerge from the trance at any time, ending the spell. The target recalls the dream perfectly upon waking. If the target is awake when you cast the spell, the messenger knows it and can either end the trance (and the spell) or wait for the target to sleep, at which point the messenger enters its dreams. You can make the messenger terrifying to the target. If you do so, the messenger can deliver a message of no more than ten words, and then the target makes a Wisdom saving throw. On a failed save, the target gains no benefit from its rest, and it takes 3d6 Psychic damage when it wakes up.', 0, 0, '["bard", "warlock", "wizard"]'),

('hold_monster', 'Hold Monster', 5, 'Enchantment', 'Action', '90 feet', 'V, S, M (a straight piece of iron)', 'Concentration, up to 1 minute', 'One creature you can see within range must succeed on a Wisdom saving throw or have the Paralyzed condition for the duration. At the end of each of its turns, the target repeats the save, ending the spell on itself on a success. Using a Higher-Level Spell Slot. You can target one additional creature for each spell slot level above 5.', 1, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

('mislead', 'Mislead', 5, 'Illusion', 'Action', 'Self', 'S', 'Concentration, up to 1 hour', 'You gain the Invisible condition at the same time that an illusory double of you appears where you''re standing. The double lasts for the duration, but the invisibility ends immediately after you make an attack roll, deal damage, or cast a spell. As a Bonus Action, you can move the illusory double up to twice your Speed and make it gesture, speak, and behave in whatever way you choose. It is intangible and invulnerable. You can see through its eyes and hear through its ears as if you were located where it is.', 1, 0, '["bard", "warlock", "wizard"]'),

('planar_binding', 'Planar Binding', 5, 'Abjuration', '1 hour', '60 feet', 'V, S, M (a jewel worth 1,000+ GP, which the spell consumes)', '24 hours', 'You attempt to bind a Celestial, an Elemental, a Fey, or a Fiend to your service. The creature must be within range for the entire casting of the spell. (Typically, the creature is first summoned into the center of the spell''s area, which prevents the creature from moving.) At the completion of the casting, the target must succeed on a Charisma saving throw or be bound to serve you for the duration. If the creature was summoned or created by another spell, that spell''s duration is extended to match the duration of this spell. A bound creature must follow your commands to the best of its ability. You might command the creature to accompany you on an adventure, to guard a location, or to deliver a message. If the creature is Hostile, it strives to twist your commands to achieve its own objectives. If the creature carries out your commands completely before the spell ends, it travels to you to report this fact if you are on the same plane of existence. If you are on a different plane, it returns to the place where you bound it and remains there until the spell ends. Using a Higher-Level Spell Slot. The duration increases with a spell slot of level 6 (10 days), 7 (30 days), 8 (180 days), or 9 (366 days).', 0, 0, '["bard", "cleric", "druid", "warlock", "wizard"]'),

('scrying', 'Scrying', 5, 'Divination', '10 minutes', 'Self', 'V, S, M (a focus worth 1,000+ GP, such as a crystal ball, mirror, or water-filled font)', 'Concentration, up to 10 minutes', 'You can see and hear a creature you choose that is on the same plane of existence as you. The target makes a Wisdom saving throw, which is modified (see the Scrying table) by how well you know the target and the sort of physical connection you have to it. The target doesn''t know what it is making the save against, only that it feels uneasy. On a successful save, the target isn''t targeted by this spell for 24 hours. On a failed save, the spell creates an Invisible, intangible sensor within 10 feet of the target. You can see and hear through the sensor as if you were there. The sensor moves with the target, remaining within 10 feet of it for the duration. If the target can see Invisible objects, it can see the sensor as a luminous orb about the size of your fist.', 1, 0, '["bard", "cleric", "druid", "warlock", "wizard"]'),

('teleportation_circle', 'Teleportation Circle', 5, 'Conjuration', '1 minute', '10 feet', 'V, M (rare inks worth 50+ GP, which the spell consumes)', '1 round', 'As you cast the spell, you draw a 10-foot-diameter circle on the ground inscribed with sigils that link your location to a permanent teleportation circle of your choice whose sigil sequence you know and that is on the same plane of existence as you. A shimmering portal opens within the circle you drew and remains open until the end of your next turn. Any creature that enters the portal instantly appears within 5 feet of the destination circle or in the nearest unoccupied space if that space is occupied. Many major temples, guilds, and other important places have permanent teleportation circles inscribed somewhere within their confines. Each such circle includes a unique sigil sequence—a string of runes arranged in a particular pattern. When you first gain the ability to cast this spell, you learn the sigil sequences for two destinations on the Material Plane, determined by the DM. You can learn additional sigil sequences during your adventures. You can commit a new sigil sequence to memory after studying it for 1 minute. You can create a permanent teleportation circle by casting this spell in the same location every day for 365 days.', 0, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

-- Level 6 Spells
('circle_of_death', 'Circle of Death', 6, 'Necromancy', 'Action', '150 feet', 'V, S, M (the powder of a crushed black pearl worth 500+ GP)', 'Instantaneous', 'Negative energy ripples out in a 60-foot-radius Sphere from a point you choose within range. Each creature in that area makes a Constitution saving throw, taking 8d8 Necrotic damage on a failed save or half as much damage on a successful one. Using a Higher-Level Spell Slot. The damage increases by 2d8 for each spell slot level above 6.', 0, 0, '["sorcerer", "warlock", "wizard"]'),

('create_undead', 'Create Undead', 6, 'Necromancy', '1 minute', '10 feet', 'V, S, M (one 150+ GP black onyx stone for each corpse)', 'Instantaneous', 'You can cast this spell only at night. Choose up to three corpses of Medium or Small Humanoids within range. Each one becomes a Ghoul under your control. As a Bonus Action on each of your turns, you can mentally command any creature you animated with this spell if the creature is within 120 feet of you (if you control multiple creatures, you can command any of them at the same time, issuing the same command to them). You decide what action the creature will take and where it will move on its next turn, or you can issue a general command, such as to guard a particular place. If you issue no commands, the creature takes the Dodge action and moves only to avoid harm. Once given an order, the creature continues to follow the order until its task is complete. The creature is under your control for 24 hours, after which it stops obeying any command you''ve given it. To maintain control of the creature for another 24 hours, you must cast this spell on the creature before the current 24-hour period ends. This use of the spell reasserts your control over up to three creatures you have animated with this spell rather than animating new ones. Using a Higher-Level Spell Slot. If you use a level 7 spell slot, you can animate or reassert control over four Ghouls. If you use a level 8 spell slot, you can animate or reassert control over five Ghouls or two Ghasts or Wights. If you use a level 9 spell slot, you can animate or reassert control over six Ghouls, three Ghasts or Wights, or two Mummies.', 0, 0, '["cleric", "warlock", "wizard"]'),

('eyebite', 'Eyebite', 6, 'Necromancy', 'Action', 'Self', 'V, S', 'Concentration, up to 1 minute', 'For the duration, your eyes become an inky void. One creature of your choice within 60 feet of you that you can see must succeed on a Wisdom saving throw or be affected by one of the following effects of your choice for the duration. On each of your turns until the spell ends, you can take a Magic action to target another creature but can''t target a creature again if it has succeeded on a save against this casting of the spell. Asleep. The target has the Unconscious condition. It wakes up if it takes any damage or if another creature takes an action to shake it awake. Panicked. The target has the Frightened condition. On each of its turns, the Frightened target must take the Dash action and move away from you by the safest and shortest route available. If the target moves to a space at least 60 feet away from you where it can''t see you, this effect ends. Sickened. The target has the Poisoned condition.', 1, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

('true_seeing', 'True Seeing', 6, 'Divination', 'Action', 'Touch', 'V, S, M (mushroom powder worth 25+ GP, which the spell consumes)', '1 hour', 'For the duration, a willing creature you touch has Truesight with a range of 120 feet.', 0, 0, '["bard", "cleric", "sorcerer", "warlock", "wizard"]'),

-- Level 7 Spells
('etherealness', 'Etherealness', 7, 'Conjuration', 'Action', 'Self', 'V, S', 'Up to 8 hours', 'You step into the border regions of the Ethereal Plane, where it overlaps with your current plane. You remain in the Border Ethereal for the duration. During this time, you can move in any direction. If you move up or down, every foot of movement costs an extra foot. You can perceive the plane you left, which looks gray, and you can''t see anything there more than 60 feet away. While on the Ethereal Plane, you can affect and be affected only by creatures, objects, and effects on that plane. Creatures that aren''t on the Ethereal Plane can''t perceive or interact with you unless a feature gives them the ability to do so. When the spell ends, you return to the plane you left in the spot that corresponds to your space in the Border Ethereal. If you appear in an occupied space, you are shunted to the nearest unoccupied space and take Force damage equal to twice the number of feet you are moved. This spell ends instantly if you cast it while you are on the Ethereal Plane or a plane that doesn''t border it, such as one of the Outer Planes. Using a Higher-Level Spell Slot. You can target up to three willing creatures (including yourself) for each spell slot level above 7. The creatures must be within 10 feet of you when you cast the spell.', 1, 0, '["bard", "cleric", "sorcerer", "warlock", "wizard"]'),

('finger_of_death', 'Finger of Death', 7, 'Necromancy', 'Action', '60 feet', 'V, S', 'Instantaneous', 'You unleash negative energy toward a creature you can see within range. The target makes a Constitution saving throw, taking 7d8 + 30 Necrotic damage on a failed save or half as much damage on a successful one. A Humanoid killed by this spell rises at the start of your next turn as a Zombie that follows your verbal orders.', 0, 0, '["sorcerer", "warlock", "wizard"]'),

('forcecage', 'Forcecage', 7, 'Evocation', 'Action', '100 feet', 'V, S, M (ruby dust worth 1,500+ GP, which the spell consumes)', 'Concentration, up to 1 hour', 'An immobile, Invisible, Cube-shaped prison composed of magical force springs into existence around an area you choose within range. The prison can be a cage or a solid box, as you choose. A prison in the shape of a cage can be up to 20 feet on a side and is made from 1/2-inch diameter bars spaced 1/2 inch apart. A prison in the shape of a box can be up to 10 feet on a side, creating a solid barrier that prevents any matter from passing through it and blocking any spells cast into or out from the area. When you cast the spell, any creature that is completely inside the cage''s area is trapped. Creatures only partially within the area, or those too large to fit inside it, are pushed away from the center of the area until they are completely outside it. A creature inside the cage can''t leave it by nonmagical means. If the creature tries to use teleportation or interplanar travel to leave, it must first make a Charisma saving throw. On a successful save, the creature can use that magic to exit the cage. On a failed save, the creature doesn''t exit the cage and wastes the spell or effect. The cage also extends into the Ethereal Plane, blocking ethereal travel. This spell can''t be dispelled by Dispel Magic.', 1, 0, '["bard", "warlock", "wizard"]'),

('plane_shift', 'Plane Shift', 7, 'Conjuration', 'Action', 'Touch', 'V, S, M (a forked, metal rod worth 250+ GP and attuned to a plane of existence)', 'Instantaneous', 'You and up to eight willing creatures who link hands in a circle are transported to a different plane of existence. You can specify a target destination in general terms, such as the City of Brass on the Elemental Plane of Fire or the palace of Dispater on the second level of the Nine Hells, and you appear in or near that destination, as determined by the DM. Alternatively, if you know the sigil sequence of a teleportation circle on another plane of existence, this spell can take you to that circle. If the teleportation circle is too small to hold all the creatures you transported, they appear in the closest unoccupied spaces next to the circle. Alternatively, you can use this spell to banish an unwilling creature to another plane. Choose a creature within reach, and make a melee spell attack against it. On a hit, the creature must succeed on a Charisma saving throw or be transported to a random location on the plane of existence you specify. A creature so transported must find its own way back to your current plane of existence.', 0, 0, '["cleric", "druid", "sorcerer", "warlock", "wizard"]'),

-- Level 8 Spells
('befuddlement', 'Befuddlement', 8, 'Enchantment', 'Action', '150 feet', 'V, S, M (a key ring with no keys)', 'Instantaneous', 'You blast the mind of a creature that you can see within range. The target makes an Intelligence saving throw. On a failed save, the target takes 10d12 Psychic damage and can''t cast spells or take the Magic action. At the end of every 30 days, the target repeats the save, ending the effect on a success. The effect can also be ended by the Greater Restoration, Heal, or Wish spell. On a successful save, the target takes half as much damage only.', 0, 0, '["bard", "druid", "warlock", "wizard"]'),

('demiplane', 'Demiplane', 8, 'Conjuration', 'Action', '60 feet', 'S', '1 hour', 'You create a shadowy Medium door on a flat solid surface that you can see within range. This door can be opened and closed, and it leads to a demiplane that is an empty room 30 feet in each dimension, made of wood or stone (your choice). When the spell ends, the door vanishes, and any objects inside the demiplane remain there. Any creatures inside also remain unless they opt to be shunted through the door as it vanishes, landing with the Prone condition in the unoccupied spaces closest to the door''s former space. Each time you cast this spell, you can create a new demiplane or connect the shadowy door to a demiplane you created with a previous casting of this spell. Additionally, if you know the nature and contents of a demiplane created by a casting of this spell by another creature, you can connect the shadowy door to that demiplane instead.', 0, 0, '["sorcerer", "warlock", "wizard"]'),

('dominate_monster', 'Dominate Monster', 8, 'Enchantment', 'Action', '60 feet', 'V, S', 'Concentration, up to 1 hour', 'One creature you can see within range must succeed on a Wisdom saving throw or have the Charmed condition for the duration. The target has Advantage on the save if you or your allies are fighting it. Whenever the target takes damage, it repeats the save, ending the spell on itself on a success. You have a telepathic link with the Charmed target while the two of you are on the same plane of existence. On your turn, you can use this link to issue commands to the target (no action required), such as "Attack that creature," "Move over there," or "Fetch that object." The target does its best to obey on its turn. If it completes an order and doesn''t receive further direction from you, it acts and moves as it likes, focusing on protecting itself. You can command the target to take a Reaction but must take your own Reaction to do so. Using a Higher-Level Spell Slot. Your Concentration can last longer with a level 9 spell slot (up to 8 hours).', 1, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

('glibness', 'Glibness', 8, 'Transmutation', 'Action', 'Self', 'V', '1 hour', 'Until the spell ends, when you make a Charisma check, you can replace the number you rolled with a 15. Additionally, no matter what you say, magic that would determine if you are telling the truth indicates that you are being truthful.', 0, 0, '["bard", "warlock"]'),

('power_word_stun', 'Power Word Stun', 8, 'Enchantment', 'Action', '60 feet', 'V', 'Instantaneous', 'You speak a word of power that can overwhelm the mind of one creature you can see within range, leaving it dumbfounded. If the target has 150 Hit Points or fewer, it has the Stunned condition. Otherwise, its Speed is 0 until the start of your next turn. The Stunned target makes a Constitution saving throw at the end of each of its turns, ending the condition on itself on a success.', 0, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

-- Level 9 Spells
('astral_projection', 'Astral Projection', 9, 'Necromancy', '1 hour', '10 feet', 'V, S, M (for each of the spell''s targets, one jacinth worth 1,000+ GP and one silver bar worth 100+ GP, all of which the spell consumes)', 'Until dispelled', 'You and up to eight willing creatures within range project your astral bodies into the Astral Plane (the spell ends instantly if you are already on that plane). Each target''s body is left behind in a state of suspended animation; it has the Unconscious condition, doesn''t need food or air, and doesn''t age. A target''s astral form resembles its body in almost every way, replicating its game statistics and possessions. The principal difference is the addition of a silvery cord that trails from between the shoulder blades of the astral form. The cord fades from view after 1 foot. If the cord is cut—which happens only when an effect states that it does so—the target''s body and astral form both die. A target''s astral form can travel through the Astral Plane. The moment an astral form leaves that plane, the target''s body and possessions travel along the silver cord, causing the target to re-enter its body on the new plane. Any damage or other effects that apply to an astral form have no effect on the target''s body and vice versa. If a target''s body or astral form drops to 0 Hit Points, the spell ends for that target. The spell ends for all the targets if you take a Magic action to dismiss it. When the spell ends for a target who isn''t dead, the target reappears in its body and exits the state of suspended animation.', 0, 0, '["cleric", "warlock", "wizard"]'),

('foresight', 'Foresight', 9, 'Divination', '1 minute', 'Touch', 'V, S, M (a hummingbird feather)', '8 hours', 'You touch a willing creature and bestow a limited ability to see into the immediate future. For the duration, the target has Advantage on D20 Tests, and other creatures have Disadvantage on attack rolls against it. The spell ends early if you cast it again.', 0, 0, '["bard", "druid", "warlock", "wizard"]'),

('gate', 'Gate', 9, 'Conjuration', 'Action', '60 feet', 'V, S, M (a diamond worth 5,000+ GP)', 'Concentration, up to 1 minute', 'You conjure a portal linking an unoccupied space you can see within range to a precise location on a different plane of existence. The portal is a circular opening, which you can make 5-20 feet in diameter. You can orient the portal in any direction you choose. The portal lasts for the duration. The portal has a front and a back on each plane where it appears. Travel through the portal is possible only by moving through its front. Anything that does so is instantly transported to the other plane, appearing in the unoccupied space nearest to the portal. Deities and other planar rulers can prevent portals created by this spell from opening in their presence or anywhere within their domains. When you cast this spell, you can name a specific creature (a pseudonym, title, or nickname doesn''t work). If that creature is on a plane other than the one you are on, the portal opens in the named creature''s immediate vicinity and draws the creature through it to the nearest unoccupied space on your side of the portal. You gain no special power over the creature, and it is free to act as the DM deems appropriate. It might leave, attack you, or help you.', 1, 0, '["cleric", "sorcerer", "warlock", "wizard"]'),

('imprisonment', 'Imprisonment', 9, 'Abjuration', '1 minute', '30 feet', 'V, S, M (a statuette of the target worth 5,000+ GP)', 'Until dispelled', 'You create a magical restraint to hold a creature that you can see within range. The target must make a Wisdom saving throw. On a successful save, the target is unaffected, and it is immune to this spell for the next 24 hours. On a failed save, the target is trapped for the duration. While affected by this spell, the creature doesn''t need to breathe, eat, or drink, and it doesn''t age. Divination spells can''t locate or perceive the target. When you cast the spell, you choose one of the following forms of imprisonment. Burial. The target is entombed deep beneath the earth in a hollow globe of magical force that is just large enough to contain the target. Nothing can pass through the globe, and no creature can teleport or use planar travel to get into or out of it. Chaining. The target has the Restrained condition and can''t be moved by any means. Hedged Prison. The spell transports the target into a demiplane that is warded against teleportation and planar travel. The demiplane is your choice of a labyrinth, a cage, a tower, or the like. Minimus Containment. The target becomes 1 inch tall and is trapped inside an indestructible gem or similar object. Light can pass through the gem normally, but the target can''t leave it except by means of a Wish spell or special magic. Slumber. The target has the Unconscious condition and can''t be awoken. During a casting of the spell, you can specify a condition that will cause the spell to end and release the target. The condition can be as specific or as elaborate as you choose, but the DM must agree that the condition is reasonable and has a likelihood of coming to pass.', 0, 0, '["warlock", "wizard"]'),

('power_word_kill', 'Power Word Kill', 9, 'Enchantment', 'Action', '60 feet', 'V', 'Instantaneous', 'You compel one creature you can see within range to die. If the target has 100 Hit Points or fewer, it dies. Otherwise, it takes 12d12 Psychic damage.', 0, 0, '["bard", "sorcerer", "warlock", "wizard"]'),

('true_polymorph', 'True Polymorph', 9, 'Transmutation', '1 action', '30 feet', 'V, S, M (a drop of mercury, a dollop of gum arabic, and a wisp of smoke)', 'Concentration, up to 1 hour', 'Choose one creature or nonmagical object that you can see within range. You transform the creature into a different creature, the creature into a nonmagical object, or the object into a creature (the object must be neither worn nor carried by another creature). The transformation lasts for the duration or until the target drops to 0 Hit Points or dies. If you concentrate on this spell for the full duration, the transformation lasts until dispelled. An unwilling creature can make a Wisdom saving throw, and if it succeeds, it isn''t affected by this spell.', 1, 0, '["bard", "warlock", "wizard"]'),

('weird', 'Weird', 9, 'Illusion', 'Action', '120 feet', 'V, S', 'Concentration, up to 1 minute', 'Drawing on the deepest fears of a group of creatures, you create illusory creatures in their minds, visible only to them. Each creature in a 30-foot-radius Sphere centered on a point within range must succeed on a Wisdom saving throw or have the Frightened condition for the duration. Whenever a Frightened target starts its turn in the spell''s area, it must succeed on a Wisdom saving throw or take 4d10 Psychic damage. On a successful save, the spell ends on that target.', 1, 0, '["warlock", "wizard"]'),

-- Additional Level 2-3 Spells
('fireball', 'Fireball', 3, 'Evocation', 'Action', '150 feet', 'V, S, M (a ball of bat guano and sulfur)', 'Instantaneous', 'A bright streak flashes from you to a point you choose within range and then blossoms with a low roar into a fiery explosion. Each creature in a 20-foot-radius Sphere centered on that point makes a Dexterity saving throw, taking 8d6 Fire damage on a failed save or half as much damage on a successful one. Flammable objects in the area that aren''t being worn or carried start burning. Using a Higher-Level Spell Slot. The damage increases by 1d6 for each spell slot level above 3.', 0, 0, '["sorcerer", "wizard"]'),

('scorching_ray', 'Scorching Ray', 2, 'Evocation', 'Action', '120 feet', 'V, S', 'Instantaneous', 'You hurl three fiery rays. You can hurl them at one target within range or at several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 Fire damage. Using a Higher-Level Spell Slot. You create one additional ray for each spell slot level above 2.', 0, 0, '["sorcerer", "wizard"]'),

('stinking_cloud', 'Stinking Cloud', 3, 'Conjuration', 'Action', '90 feet', 'V, S, M (a rotten egg)', 'Concentration, up to 1 minute', 'You create a 20-foot-radius Sphere of yellow, nauseating gas centered on a point within range. The cloud is Heavily Obscured. The cloud lingers in the air for the duration or until a strong wind (like that created by Gust of Wind) disperses it. Each creature that starts its turn in the Sphere must succeed on a Constitution saving throw or have the Poisoned condition until the end of the current turn. While Poisoned in this way, the creature can''t take an action or a Bonus Action.', 1, 0, '["bard", "sorcerer", "wizard"]'),

('insect_plague', 'Insect Plague', 5, 'Conjuration', 'Action', '300 feet', 'V, S, M (a locust)', 'Concentration, up to 10 minutes', 'Swarming locusts fill a 20-foot-radius Sphere centered on a point you choose within range. The Sphere is Lightly Obscured and Difficult Terrain. Each creature in the Sphere makes a Constitution saving throw, taking 4d10 Piercing damage on a failed save or half as much damage on a successful one. A creature also makes this save when it enters the spell''s area for the first time on a turn or ends its turn there. Using a Higher-Level Spell Slot. The damage increases by 1d10 for each spell slot level above 5.', 1, 0, '["cleric", "druid", "sorcerer"]'),

('wall_of_fire', 'Wall of Fire', 4, 'Evocation', 'Action', '120 feet', 'V, S, M (a piece of charcoal)', 'Concentration, up to 1 minute', 'You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick. The wall is opaque and lasts for the duration. When the wall appears, each creature in its area makes a Dexterity saving throw, taking 5d8 Fire damage on a failed save or half as much damage on a successful one. One side of the wall, selected by you when you cast this spell, deals 5d8 Fire damage to each creature that ends its turn within 10 feet of that side or inside the wall. A creature takes the same damage when it enters the wall for the first time on a turn or ends its turn there. The other side of the wall deals no damage. Using a Higher-Level Spell Slot. The damage increases by 1d8 for each spell slot level above 4.', 1, 0, '["druid", "sorcerer", "wizard"]');

-- Note: These spells should already have entries in spell_class_lists table
-- This migration only adds them to the spells table
